### ISSUE TITLE
Tooling sprint - Week 07 - 2019

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13574]
- [x] [trigger discussion and initial changes of API docs revamp ](https://github.com/ballerina-platform/ballerina-lang/issues/13548)

- [x] [Usability test and review](https://github.com/ballerina-platform/ballerina-lang/issues/13541)

- [x] [Review current work on Che](https://github.com/ballerina-platform/ballerina-lang/issues/13565)

- [x] [API Designer Hackathon](https://github.com/ballerina-platform/ballerina-lang/issues/13567)

- [x] [Start work on function expand/collapse](https://github.com/ballerina-platform/ballerina-lang/issues/13546)

- [x] Design review of Language Client for IntelliJ Idea

- [x] [Finish off gradle build for tooling modules](https://github.com/ballerina-platform/ballerina-lang/issues/13569)

- [ ] Formatting guidelines review 

- [ ] Discussion on adding formatting guidelines to site

- [x] [Revamp Language Server Compiler Package Cache](https://github.com/ballerina-platform/ballerina-lang/issues/13530)

- [x] [Document Symbol and Workspace symbol descriptions show non-alphanumeric characters](https://github.com/ballerina-platform/ballerina-lang/issues/13536)
- [ ] [Text Edit support with Completion static snippets](https://github.com/ballerina-platform/ballerina-lang/issues/13535)
- [ ] [Revamp Goto Definition in current Package](https://github.com/ballerina-platform/ballerina-lang/issues/13529)
