### ISSUE TITLE
Swagger tooling refactoring

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-lang#13588]
**Description:**
This task is created to track the progress of the Ballerina Swagger tooling redesign and refactoring. 

- [x] Discuss the naming of the tool
- [x] Rename Ballerina Code generator which generate Client for a service using openAPI specification. https://github.com/ballerina-platform/ballerina-lang/issues/13807
- [x] Write a spec for the tool.
  - [x] Review the mapping details of the spec.
    - [x] 1st review
  - [x] Share the designs with community.
- [x] Design how to show the swagger details on Ballerina Source
- [ ] Upgrade swagger library versions to the latest https://github.com/ballerina-platform/ballerina-lang/issues/14538
- [ ] Handle all content type in conversion from ballerina or to ballerina 
- [ ] Update Ballerina by Guides for swagger
- [ ] Add warning for swagger annotation resolver for what was not possible to convert in to swagger
- [x] Rename swagger tool - https://github.com/ballerina-platform/ballerina-lang/issues/13807
- [x] Refactor and improve usability of CLI command 
- [x] Refactor the CLI help files
- [x] Move on to generate Open API 3.0 (e.g: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml) 
- [x] Test with OpenAPI 3.0 https://github.com/ballerina-guides/open-api-based-service/issues/35

##### Swagger to Ballerina #####

- [ ] Fix data losses during this conversion
- [ ] Improve support for schemas, parameters, responses, requestBody
- [ ] Improve template for generating ballerina source

##### Ballerina to Swagger #####
- [ ] Fix data losses during this conversion
- [ ] Support conversion for all types
- [ ] Support conversion for parameters, responses, requestBody

###### Related issues
https://github.com/ballerina-platform/ballerina-lang/issues/12518
https://github.com/ballerina-platform/ballerina-lang/issues/13018

**Comment by NipunaMarcus** [comment]
Review Notes for the OpenAPI Spec

-

**Comment by NipunaMarcus** [comment]
Review of OpenAPI Tooling Spec

- [x] Remove unnecessary details from the spec.
- [ ] Look in to whether we can move the OpenAPI object level description to markdown documentation
- [ ] Create a annotation in service level to hold common details available for path item object which are not captured in resource function and resource annotations
- [ ] Discuss with standard library team about mappings like required attribute in Parameter object to ballerina optional type in ballerina source.

**Comment by NipunaMarcus** [comment]
Moved to a new issue #16935
