### ISSUE TITLE
Tooling sprint - Week 08 - 2019

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13652]
#### Usability Test
- [x] Send PRs for BBG issues found
- [x] Create issues for bugs/improvements on tooling
- [ ] send an update to dev list

#### API Docs Revamp https://github.com/ballerina-platform/ballerina-lang/issues/13548
- [x] Merging dependabot PRs for javascript
- [x] #13737 
- [x] #13700
- [ ] Fix construct categories (eg:Client , Errors)
- [ ] improve TOC structure 
       - make categories prominent

#### Required Reviews
- [ ] Diagram usability
- [ ] OpenAPI designer
- [ ] Idea LS Plugin 
- [x] LS compiler module cache
- [x] Go to definition initial revamp design review
- [ ] Formatter implementation

#### OpenAPI Designer (https://github.com/ballerina-platform/ballerina-lang/issues/13588)
- [ ] Backend fixes - Focus on making sure the generated code for complex (k8s) scenarios are not broken.
- [ ] Swagger -> OpenAPI rename (https://github.com/ballerina-platform/ballerina-lang/issues/13807)

#### Diagram
- [ ] [Function collapse/expand initial working version](https://github.com/ballerina-platform/ballerina-lang/issues/13546)

#### Idea Plugin
- [ ] Incorporate suggested fixes during initial review
- [x] Code actions support through LS
- [x] Repository restructure
          - Keep library and plugin in a single repo
          - A new branch for ballerina-idea-ls-plugin
          - Maven org/ copyrights

#### Build (Gradle) (https://github.com/ballerina-platform/ballerina-lang/issues/13569)
- [ ] Sync with master
- [ ]  Enabling cover coverage tools
- [ ] Migrating documentation

#### Formatting (https://github.com/ballerina-platform/ballerina-lang/issues/13280)
- [ ] Discussion on adding formatting guidelines to site
- [x] fix error types source gen & formatting - https://github.com/Anoukh/ballerina-lang/pull/4

#### Lang-Server

- [x] [Text Edit support with Completion static snippets](https://github.com/ballerina-platform/ballerina-lang/issues/13535)
- [x] [Revamp Rename symbols](https://github.com/ballerina-platform/ballerina-lang/issues/13529)
- [x] [Use workspace edits to create tests](https://github.com/ballerina-platform/ballerina-lang/issues/13532)

**Comment by kaviththiranga** [comment]
Closing and moving remaining task to next sprint https://github.com/ballerina-platform/ballerina-lang/issues/13848
