### ISSUE TITLE
Ballerina Task List for 0.995 Release

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-lang#13741]
This issue summarizes all the features that will be available for 0.995 release.  

#### jBallerina
* Types and Values
    - [x] #13852 Representing ballerina values in JBallerina
    - [x] #13855 Representing ballerina types in JBallerina
    - [x] #13856 Type checking related operations in JBallerina
    - [x] #13857 Value manipulations in JBallerina

* BIR
    - [ ] #13873 BIR model and design
* Strand Implementation
    - [x] #13887 Strand modeling and implementation for JBallerina
* Compiling and running ballerina modules as .jar
    - [x] #13868 Compile ballerina modules to .jar
    - [x] #13869 Run compiled .jar
    - [x] #13870 Global variables in JBallerina
* Debugging support
* Error handling and stack trace
* Java interoperability
* Services and clients
* jBallerina commands and distribution

### 2019R1 Spec compliance

* Tuple and Record syntax rework.
* Annotation Definition rework.
* Constant improvements.
* Taint handling rework.
* Defaults values in Function/Record rework.

Full List of tasks is maintained here. https://github.com/ballerina-platform/ballerina-lang/projects/7

### Ballerinax
 - [ ] https://github.com/ballerinax/kubernetes/issues/292 Kubernetes Connector
 - [ ] https://github.com/ballerinax/kubernetes/issues/293 Deploy a ballerina service with one command 

#### Messaging 
- [ ] #13810  Introduce NATS Connector
- [ ] #13812  Introduce RabbitMQ Connector 
- [ ] #13814 Introduce Artemis Connector 

#### Path/URL
- [x] #13811  Introduce PATH APIs for Ballerina
- [ ] #15157 Add filepath specific system operations to system module

#### Testing and Automation
- [ ] #13813  Investigate performance improvement areas on Ballerina components
- [ ] #13888 Implement Ballerina scenario Tests(End to End Tests) on Testgrid
  - [ ] #13815  Facilitate BBG automation with TestGrid

#### HTTP
- [x] #12815 A memory leak while load testing for invalid request path, but valid host-name and port
- [ ] #9756 Transport errors get caught by the topmost handler of the netty pipeline
- [ ] Support multiple Error types
- [ ] #6908 Remove forwarded config and add it as a optional param to client actions
- [ ] #13874 Improve content negotiation based on the Produces config
- [ ] Extend LB pluggable algorithm support
- [x] #13847 #13846 Introduce configuration options to SSL handshake/session timeouts
- [x] #13912 Upgrade Netty version
- [ ] #6902 Test the code for different failure scenarios
- [x] #14041 Content type validation should be removed from request and response payload getter APIs
- [x] #13877 Improve HTTP/2 client connection pool
- [ ] #11054 Validate CB, LB and FO on HTTP/2
- [ ] #13871 Make HTTP/2 as default transport
- [x] #11371 Add flow control support to HTTP/2
- [x] #14380 [HTTP/2] Handle exhausted Stream Id for client
- [ ] #11369 Introduce a config for both the HTTP/2 client and server to define SETTINGS_MAX_CONCURRENT_STREAMS
- [ ] #11045 Handle exception scenario while writing contents
- [ ] #11027 Verify the invalid state actions with reference to the specification
- [x] #14301 TPS is lower in HTTP/2 server downgrade scenario compared to HTTP/1.1
- [x] Stabilize performance scenarios
  - [x] #13704 An error rate gets occurred in perf test done for http/2 scenario (H2-H1C)
  - [x] #13883 An error rate gets occurred in perf test done for http/1.1 scenario (H1_H1)
  - [x] #13705 TPS is lower in HTTP/2 than HTTP/1.1 for passthrough scenario
  - [x] #13885 An error rate gets occurred in perf test done for http/2 scenario (H2_H1)
- [x] #13923 Performance test for upgrade/downgrade scenarios
  - [x] #13927 An error rate gets occurred in perf test done for http/2 client upgrade scenario (H1C_H2C_Client_Upgrade)
  - [x] #13953 An error rate gets occurred in perf test done for http/2 server downgrade scenario (H2_H2_Server_Downgrade)
  - [x] #13954 An error rate gets occurred in perf test done for http/2 server downgrade scenario (H2C_H2C_Server_Downgrade)
- [ ] #14075 Need to write test cases to cover HTTP/2 scenarios in transport
- [x] #14472 Add support for prior knowledge in transport test backend and enable relevant tests
- [ ] #14953 Provide first class support for essential request and response properties in carbon message
- [ ] #15143 [HTTP/2] Allow changing initial window size value for both the client and the server
- [x] #15301 Add prior knowledge support to ballerina HTTP/2 client
- [x] #15360 Seperate HTTP/1 settings from HTTP/2 settings in ClientEndpointConfig

#### Data
- [x] #13817  Introduce global shared connection pool for database clients
- [x] #14024 Refactor SQL Update function API
- [ ] #13503 Allow having union type fields for record types as the constraints of tables returned from data client operations
- [x] #13586 Support Decimal Data type
- [ ] #13816  Automate DB tests on TestGrid

#### Time
- [x] Refactor Time API

#### Message Transformation
- [ ] Implement XSLT support

#### I/O
- [x] #13908 Implement UDP socket support - Client
- [x] #13906 Implement read action for TCP socket

#### Task
- [x] #13632  Redesign Task library

#### Security
- [x] Reorganize and improve outbound authentication
  - [x] #10478 JWT token propagation configs should be moved to client-endpoint Auth config section  
  - [x] #10468 Tokens keep getting refreshed when OAuth2 client-id is shared across multiple HTTP clients
  - [x] #13525 Improve OAuth2 support for revoking refresh token for client authentication 
  - [x] #10459 Implement support for OAuth2 client-credentials & password grant type for client authentication
  - [x] #15487 Decouple HTTP outbound authentication mechanisms
- [x] Reorganize and improve inbound authentication
  - [x] #10471 Improvements to authentication & authorization API
  - [x] #14823 Custom handler and provider engagement support for HTTP inbound authentication
  - [x] #10474 OAuth2 inbound authentication support
  - [x] #11158 Support PBKDF2 and BCrypt based password hashing for basic-auth passwords
  - [x] #11321 Separate inbound and outbound authentication configuration
  - [x] #11528 [JWT] Require predefined JWT Header algorithms
  - [x] #13325 [Auth] Authorization failure when engaging empty scopes for HTTP service config
  - [x] #9792 Move JWT token creation related functions out of internal pkg
  - [x] #15385 Update Module Structure for Ballerina Inbound Authentication 
  - [x] #14966 Support Multiple Trusted JWT Issuers in JWT Validator
- [x] Reorganize and improve crypto library
  - [x] #4388 #9764 Improve hash functions to generate byte[] (instead of encoded string)
  - [x] #4388 Create separate functions for different crypto algorithms
  - [x] #4388 Research on commonly required encryption and hashing functions and introduce those to crrypto API
  - [x] #12568 #9767 Provide encoding functions to encode byte[] into base64, hex, etc.
  - [x] #13135 Add support for signing using RSA-SHA256 algorithm
  - [x] #9054 Add RSA and AES encryption/decryption capabilities to crypto stdlib
  - [x] #10733 SSL related configuration options should come from a unified location

#### WebSub
- [ ] #13875 Add BBG including persistance and basic auth capabilities

#### Diagram
- [ ] #13544 Graphical Debugging support in diagram
- [ ] #13546 Function invocation expand/collapse in diagram
- [ ] #13549 Diagram code refactor
- [ ] #13551 Ship diagram with the distribution

#### VSCode Extension
- [ ] #13561 VSCode dark & light theme support
- [ ] #13541 Fix usability issues in VSCode plugin
- [ ] #13556 Improve VSCode test coverage
- [ ] #13564 Creating a record from a JSON

#### Language Server
- [ ] #14214 Performance improvements (for completions & diagnostics) refer [thread](https://groups.google.com/d/msg/ballerina-dev/YjfbZtH7z9o/lVCXySp2AAAJ)
- [ ] #13534 Chained completions
- [ ] #14216 Source pruning based context resolving
- [ ] #14054 Extension support for Language Server Completions
- [ ] #13529 Revamp Goto Definition, Find all References and Rename
- [ ] #13541 Bug fixes

#### Formatter  #13280
- [ ] [Opinionated style guide for Ballerina programs](https://github.com/NipunaMarcus/ballerina/tree/master/docs/style_guide)
- [ ] Implementation to support all or subset of rules
- [ ] CLI command for formatting

#### API Docs #13548
- [ ] Improve generated API docs
- [ ]  Introduce a portable output format

#### Intellij Idea Plugin #13991
- [x] Lang server client for Idea
- [ ] Lang-Server based diagnostics, completions & go-to-def support
- [ ] Diagram rendering and Editing

#### JBallerina compatibility #13566
- [ ]  Debugging support
- [ ]  Coverage support

#### OpenAPI tools #13588
- [x]  Swagger to OpenAPI rename #13807
- [ ]  API Designer improvements
- [ ] Revisit data mapping annotation
- [ ] Generate k8s API client with k8s OpenAPI spec
- [ ] Auto generate clients for services

####  Eclipse Theia & Che #13565
- [x] Get VSCode extension running on Theia
- [ ] Eclipse Che support

## Connectors
- [ ] Implement SAP Connector

**Comment by anupama-pathirage** [comment]
Closing this as this milestone is already done
