### ISSUE TITLE
Similar to MySQL, H2 add separate clients for Oracle, PostgreSQL etc

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#13818]
- [ ] #14107 Enhance MySQL client implementation 
- [ ] #14108 Introduce separate client for postgresql
- [ ] #14109 Introduce separate client for Oracle

**Comment by anupama-pathirage** [comment]
This effort is postponed until we get the nBallerina support. 
The advantages we get by having DB specific connectors are:
- Support DB specific features which cannot be supported by JDBC spec.
- Client connector configs can be more DB specific to have first class support for those parameters. 

But until we get nBallerina still the underlying implementation will be JDBC. So user has to copy the relevent JDBC driver to use DB specific module. And we can live with the features supported by JDBC. So  there is no real value by adding new modules at this point. So decided to go with following two modules only.
- jdbc
- h2  - This can be also done with jdbc. But to get the examples running and to test db specific use cases with ballerina without having driver get copied, we will support this.

Hence closing this issue.
