### ISSUE TITLE
Tooling Sprint - Week 09 - 2019

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#13848]
#### Usability Test
- [x] send an update to dev list

#### API Docs Revamp https://github.com/ballerina-platform/ballerina-lang/issues/13548
- [x] improve TOC structure 
       - make categories prominent

#### Required Reviews
- [ ] Diagram usability
- [ ] OpenAPI designer
- [x] Idea LS Plugin 
- [ ] Formatter implementation

#### OpenAPI Designer (https://github.com/ballerina-platform/ballerina-lang/issues/13588)
- [ ] Backend fixes - Focus on making sure the generated code for complex (k8s) scenarios are not broken.
- [ ] Swagger -> OpenAPI rename (https://github.com/ballerina-platform/ballerina-lang/issues/13807)

#### Diagram
- [x] [Function collapse/expand initial working version](https://github.com/ballerina-platform/ballerina-lang/issues/13546)

#### Idea Plugin - [roadmap](https://github.com/ballerina-platform/ballerina-lang/issues/13991)
- [x] Incorporate suggested fixes during initial review
- [ ] Keep library and plugin in a single repo
- [x] A new branch for ballerina-idea-ls-plugin in ballerina-lang repo
- [ ] Maven org/ copyrights
- [x] Add capability of supporting multiple file types for a single language server instance 

#### Build (Gradle) (https://github.com/ballerina-platform/ballerina-lang/issues/13569)
- [x] Fix issues after stdlib refactoring
- [x] Fix maven build and merge branch to master
- [x] Configure travis to run maven and gradle in parallel jobs
- [x] Fix incorrect resource paths in java tests

#### Formatting (https://github.com/ballerina-platform/ballerina-lang/issues/13280)
- [x] Discussion on adding formatting guidelines to site
- [ ] Finish formatting guidelines docs(https://github.com/ballerina-platform/ballerina-lang/issues/13862)

#### Lang-Server
- [x] Perf improvements based on micro gateway project
- [ ] [Introduce SPIs for Completions](https://github.com/ballerina-platform/ballerina-lang/issues/13928)
- [x] Find references implementation revamp
- [x] Goto definition, rename and find all references within multiple modules in the same project
