### ISSUE TITLE
Language sprint - Week 09 - 2019

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#13853]
0.990.0 Spec deviations. 
- [ ] #13190 In an XML sequence, a character set is treated as a single string. However, in the specification, each character item is represented by a string with a single code point.
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/13849 Variable Mutability in Closures
- [ ] #13317, #13820: Inter-assignability between float, decimal constants and byte, int constants in a union type is allowed currently. Which is not the expected behavior. [WIP]
- [ ] #13587: `isAssignableToFiniteType` method of `Types` class needs to be modified [WIP]
- [ ] #13889: Introduce error binding pattern
- [x] #13164: Support expressions for tuple index based access
- [ ] #13838: Improvements to finite types 
- [ ] #13804: `is` check not allowed for union types that have an intersection 
- [x] #13654: Incorrect type checking for the reason specified in the error constructor
- [ ] #13619: Module level variables cannot be public
- [ ] #13899: Add map literal support to constants
- [ ] #13900 Forward reference reordering needs to support Services and Objects
- [ ] #13342 Object __init() methods return should be a subtype of error|()
- [ ] #13903 Implicit init values of union types are only applicable when constituents are of same simple basic type

Compiler internals improvement
- [x] #13902 Flatten the union type

Streaming
- [ ] Prioritize the pattern processors based on their importance.
- [ ] Design the very basic pattern processor (The basic state machine)
- [x] #14027 Blog on implementing custom windows
- [x] #14029 Fix intermittent test failures in streams

Language extensions  (k8s, docker etc.)
- [x] https://github.com/ballerinax/kubernetes/issues/268 Typo in kubernetes error message
- [x] https://github.com/ballerinax/kubernetes/issues/267 Config files are looked up at where ballerina command is run and not where the ballerina file is at.
- [x] https://github.com/ballerinax/kubernetes/issues/164 Add Support for OpenShift
- [x] https://github.com/ballerinax/kubernetes/issues/283 Error when deployment generated kubernetes artifacts

@gimantha @grainier @pubudu538 @MaryamZi @Anoukh @Shan1024 @pranavan15 @rdhananjaya @hemikak @NatashaWso2 @sameerajayasoma

**Comment by hasithaa** [comment]
PRs ready, 

https://github.com/ballerina-platform/ballerina-lang/pull/13893
https://github.com/ballerina-platform/ballerina-lang/pull/13967
https://github.com/ballerina-platform/ballerina-lang/pull/13932
https://github.com/ballerina-platform/ballerina-lang/pull/14032
https://github.com/ballerina-platform/ballerina-lang/pull/13920

**Comment by hasithaa** [comment]
Open task were move to https://github.com/ballerina-platform/ballerina-lang/issues/14038
