### ISSUE TITLE
StdLib sprint - Week 09 - 2019

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#13878]
#### HTTP
- [x] GetPayload method non-blocking code review
~~- #13874 Improve content negotiation based on the Produces config~~
- [x] #13880 Update apacheds-all version
- [x] #13885 An error rate gets occurred in perf test done for http/2 scenario (H2_H1)
- [x] #13883 An error rate gets occurred in perf test done for http/1.1 scenario (H1_H1)
- [x] #13923 Performance test for upgrade/downgrade scenarios
- [x] #13847 #13846 Introduce configuration options to SSL handshake/session timeouts
- [x] Improve HTTP/2 client connection pool
~~- #14189 Introduce eventloop pool for HTTP/2 client connections~~
- [x]  #13704 An error rate gets occurred in perf test done for http/2 scenario (H2-H1C)

#### Scenario test effort
- [x] #13891 Refactor scenario HTTP test scripts
- [x] #13996 Refactor scenario Data test scripts
- [x] #13997 Separate cluster/db creation etc logic into reusable functions

#### Data
- [x] #14024 Refactor SQL Update function API

#### Messaging 

[Implementation]

- [x] #13810 NATS basic producer 
- [ ]  #13810 NATS basic consumer
- [x]  #13812 RabbitMQ simple producer
- [ ]  #13812 RabbitMQ simple consumer
- [x] #13814 Artemis connector basic implementation

[Design]

- [x] #13810 NATS design v1

#### gRPC
- [x] #13884 Decouple connection pool in gRPC client
- [x] #13976 Fix intermittent test failure in bidirectional streaming example

#### Path
[Design]
- [ ] #13811 Finalize Path api design in Ballerina(Moved to next sprint)

[Implementation]
- [x] #13811 Implement new Path api in Ballerina(absolute() and isAbsolute() function completed with test)

#### Task
- [x] Implement a wrapper object for `Listener` to add library functionalities. 
- [x] Improve test coverage
- [x] Code review
- [x] Address code review suggestions

#### Socket
- [x] Code review for the read action implementation
