### ISSUE TITLE
JBallerina sprint - Week 09 - 2019

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#13876]
* BIR Model
    - [x] Support for import packages in BIR
         - [x] #13986 Import module declarations in BIR
         - [x] #14026 Module resolution capability to JVM Codegen
    - [x] Type def support in BIR (record, object , union type, public type alias)
    - [x] Global variables support in BIR

- [x] Strand Implementation

* Values and types
    - [x] Iterator design
    - [ ] Futures design
    - [ ] Channels design
    - [x] Tables design
    - [] "map" and "array" implementation
         - [x] https://github.com/ballerina-platform/ballerina-lang/pull/14039
         - [x] https://github.com/ballerina-platform/ballerina-lang/pull/14031
         - [x] https://github.com/ballerina-platform/ballerina-lang/pull/14077
         - [x] https://github.com/ballerina-platform/ballerina-lang/pull/14071

* Error handling Design
    - [x] Error Type and values, Trap, Panic and Stacktrace

- [x]  #13882 JVM stdlib refactor

* Compile ballerina modules to .jar 
    - [x] #14036 Update build command to build modules with jvmTarget flag
    - [x] Compile imported modules to a single jar

@SupunS @manuranga @lankavitharana @vinok88 @warunalakshitha @sameerajayasoma

**Comment by vinok88** [comment]
Refer this [doc](https://docs.google.com/document/d/1sLrgBLfCQVnzWswg5wXudzbVoiCq1n_oojLVRQnEWjs/edit?usp=sharing for) for values and types designs.
