### ISSUE TITLE
Implement const support

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#13944]
## Tasks.

- [ ]  Const support is only added for boolean literals, int literals, floating point literals, and string literals.
- [ ]  Record literal constant.
- [ ]  Support simple-constant-literals for xml namespace declarations.

@Shan1024 Please list down missing parts.

**Comment by rdhananjaya** [comment]
I think we also need to support constants of named integer subtypes.
As of swanlake alpha-4 it says `constant cannot be defined with type 'int:Signed32', expected a simple basic types or a map of a simple basic type`

**Comment by prakanth97** [comment]
unary-expr is fixed in https://github.com/ballerina-platform/ballerina-lang/pull/30693. Shall update the description?

**Comment by gayalkuruppu** [comment]
IMO constant expression `list-constructor-expr` here is a somewhat highly used scenario in coding. Better if we can prioritise that case. WDYT?
