### ISSUE TITLE
StdLib sprint - Week 10 - 2019 

### ISSUE THREAD

**Issue by wggihan** [ballerina-platform/ballerina-lang#13999]
#### HTTP
- [x] #12815 A memory leak while load testing for invalid request path, but valid host-name and port
- [x] #14072 Finalise the design to Implement a way to plug different load balance and fail-over algorithms
- [x] #13923 Performance test for upgrade/downgrade scenarios
- [x] #13877 Improve HTTP/2 client connection pool
      #14187 Distribute HTTP/2 client request load properly among I/O threads
- [x] Fix gradle build test failures in HTTP module

#### Message Transformation
- [x]  Implement XSLT support

#### Runtime module
- [x] #14144 Stabilize runtime module in gradle build

#### Scenario Test Effort
- [x] #14250 Fix issues in deployment stage with the static cluster
- [x] [ballerina-platform/aws-ballerina#13997](https://github.com/ballerina-platform/aws-ballerina/issues/2) Fix resource cleanup issues on AWS
- [x] #14192 Implement a way to run Ballerina scenario test with testNG

#### Messaging
- [x] #13810 NATS basic consumer
- [x] #13812 RabbitMQ simple consumer
- [x] #13814 Create testcase for Artemis Connector

#### gRPC
- [x] #14081 Fix test failure in gradle build

#### Path
[Design]
- [x] #13811 Finalize Path api v1 design in Ballerina

#### SOAP
- [x] Do research on pros, cons, other languages support for SOAP and read SOAP specification.

[Implementation]
- [x] #13811 Implement new Path api v1 in Ballerina

#### Socket
- [x] #13908 Implement UDP socket support - Client
