### ISSUE TITLE
Ballerina IntelliJ Plugin Roadmap

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#13991]
**Description:**

This includes the milestone plan of the ballerina intellij idea plugin.

**Java Language Client Implementation [ ETA - End of Q1 ]**

- [x] Initial POC 
- [x] Feature Implementation
  - [x] Code Completion 
  - [x] Diagnostics 
  - [x] Code Actions 
  - [x] Goto Definition 
  - [x] Find References
  - [x] Signature Help
  - [x] Hover Support 
  - [x] Code Formatting 
  - [x] Workspace Symbols
  - [x] Rename Support
- [ ] Plugins and tools integration
  - [x] Travis CI
  - [ ] Appveyor CI
  - [x] Gradle licence plugin
  - [x] Gradle release plugin
  - [x] Gradle maven publish plugin 
  - [x] Gradle signing plugin
- [x] Documentation
- [x] Publish artifacts using Jitpack
- [x] Partial Integration with ballerina IDEA plugin
- [x] Add support for multiple file extensions for a single language server (User request)
- [x] Publish to Maven Central
- [x] Remove plugin implementation for resolving, inspections and indexing
- [x] Publish ballerina plugin with java client library ( version 0.991.0 )
- [ ] Implement persistent settings holder and related UI components for lsp4intellij plugin
- [ ] Jetbrains plugin release

**Extended Language server features implementation [ ETA - Q2 ]**
- [x] Diagram Viewer
- [x] Diagram Editing Support
- [x] Debugger Adapter Protocol Support
- [x] Ballerina Home Auto Detection
