### ISSUE TITLE
Language sprint - Week 10 - 2019

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14038]
## 0.990.0 Spec deviations.

* [ ] #13849 Variable Mutability in Closures
* [ ] #13838,  #13804: Improvements to finite types & `is` check not allowed for union types that have an intersection  PR : https://github.com/ballerina-platform/ballerina-lang/pull/13931
* [ ] #13899: Add map literal support to constants
* [ ] #13342 Object __init() methods return should be a subtype of error|()
* [ ] #13946 XML Expression Improvements for 0.990.0 Spec
* [ ] #13821: Ballerina byte type needs to be refactored to use the long registry and needs to be treated similarly to int
* [ ] #13865: Arithmetic operations on byte type need to be supported
* [ ] #14012 : default' is used to define the default worker in a function so it should be treated as a keyword 
* [ ] #13583 Support const in static match statment
* [x] #13209 Client objects with no remote methods should be allowed
* [ ] #14067 Support expressions in record index based access
* [ ] #14065 Support type cast with errors
* [ ] #13655 Invalid result on `is` check as user defined error type
* [ ] #13230 Inherent type violating updates allowed in type-widening contexts for tuples
* [ ] #13171 The detail mapping value of an error type should be a frozen value 
* [ ] #13205 Detail type descriptor of Error type descriptor should be sub type of `map<anydata|error>`
* [x] #14112 Remove Symbolic string literals support from compiler
* [x] #14114 Change Array length syntax
* [x] #13204 XML grammar needs to be updated in builtInReferenceTypeName
* [x] #14106 XML type isn't support when the tag is start with "_-"

### PR ready from Previous Sprint.

* [x] #13587: isAssignableToFiniteType method of Types class needs to be modified [WIP]
* [ ] #13899: Add map literal support to constants
* [x] #13903 Implicit init values of union types are only applicable when constituents are of same simple basic type

* [x] #13190 In an XML sequence, a character set is treated as a single string. However, in the specification, each character item is represented by a string with a single code point.  PR : #13893
* [ ] #13900 Forward reference reordering needs to support Services and Objects PR #13920
* [x] #13317, #13820: Inter-assignability between float, decimal constants and byte, int constants in a union type is allowed currently. Which is not the expected behavior. PR #13967
* [x] #13889: Introduce error binding pattern PR: #13932
* [x] #13619: Module level variables cannot be public PR #14032

## Streaming

 * [ ] Prioritize the pattern processors based on their importance.
 * [ ] Design the very basic pattern processor (The basic state machine)
 * [ ] #14037 Come up with a different approach to receive events into streams instead of using MB topics
* [ ] #14035 Write a walk-thru/tutorial like blog on implementing a custom window
* [ ] #14126 Intermittent failure - BallerinaStreamsV2TimeLengthWindowTest.testTimeLengthQuery1
* [ ] #14200 Streams tests are not working in the gradle build

## Language extensions (k8s, docker etc.)
* [x] https://github.com/ballerinax/docker/issues/125 Add copy directory support to Docker extenstion
* [x] https://github.com/ballerinax/kubernetes/issues/259 Add RedinessProbe support
* [x] https://github.com/ballerinax/kubernetes/issues/288 Improve Liveness Probe fields

## Packerina
* [x] https://github.com/ballerina-platform/ballerina-lang/issues/13892 Invalidate pulled modules in the local cache when building and pulling modules using the nightly build
* [x] https://github.com/ballerina-platform/ballerina-lang/issues/13519 'ballerina pull' should pull the latest version of the module from Ballerina Central which is compatible to the ballerina version used by the developer
* [x] https://github.com/ballerina-platform/ballerina-lang/issues/13957 cannot resolve module 'wso2/github4'
* [x] https://github.com/ballerina-platform/ballerina-lang/issues/13520 [Ballerina Central] "Last Updated" value shown on a package view has the wrong value.

## Compiler
* [x] #14074 Record literals allow duplicate keys in certain cases

## Gradle Migration
* [x] Unit tests. PR #14123 and Fix for windows tests. PR #14156 
* [ ] Testerina. PR #14178
* [ ] Spec conformance tests. PR #14178
* [x] Test failures in docerina. PR #14191

## Observability
* [x] Update metrics registry with correct descriptions. PR #14022

@gimantha @grainier @pubudu538 @MaryamZi @Anoukh @Shan1024 @pranavan15 @rdhananjaya @hemikak @NatashaWso2 @sameerajayasoma

**Comment by hasithaa** [comment]
Unclosed Items has been moved to https://github.com/ballerina-platform/ballerina-lang/issues/14212.
