### ISSUE TITLE
Tooling Sprint - Week 10 - 2019

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#14042]
#### Usability Test
- [ ] Go through the issues - prioritize 

#### [API Docs](https://github.com/ballerina-platform/ballerina-lang/issues/13548)
- [x] [Finish initial spec](https://docs.google.com/document/d/1eyiduNRrUtqoL_e9AksM8B3ClRW0T-RzTrH_qwJZZjU/edit#heading=h.uwzrptniasas)
- [ ] Spec review
- [x] POC - keeping all content in md and a SPA to serve them

#### LangServer
- [x] Improve completion with source pruning before antlr parser - [Spec] - @nadeeshaan (https://docs.google.com/document/d/1Q_DIhp_c624_6mos1eW1WbatjBwnUKZ3Dv7h_VCqxbs/edit)
- [x] [Introduce SPIs for Completions](https://github.com/ballerina-platform/ballerina-lang/issues/13928) - @rasika 
- [ ] [Add new test cases for gotodef, findref, rename](https://github.com/ballerina-platform/ballerina-lang/issues/13529) - @nadeeshaan 

#### OpenAPI Designer (https://github.com/ballerina-platform/ballerina-lang/issues/13588)
- [ ] Swagger -> OpenAPI rename effort (https://github.com/ballerina-platform/ballerina-lang/issues/13807) - Work In Progress - @DimalChandrasiri 

#### Diagram
- [ ] [Function Collapsing - In Progress](https://github.com/ballerina-platform/ballerina-lang/issues/13546)
  - [x] Add a frame around the expanded function
  - [x] Add expander and collapser
  - [ ] Handle invocations that cannot be collapsed (native code)
  - [x] Fix rendering return statements of expanded functions

#### Idea Plugin - [roadmap](https://github.com/ballerina-platform/ballerina-lang/issues/13991) -  @NipunaRanasinghe 
- [ ] Publish to maven central
- [x] Goto Definition through LS
- [x] Improve documentation
- [x] Integrate the following plugins
     - [x] license/copyright plugin
     - [x] release plugin
     - [x] maven publish plugin   
     - [x] maven signing plugin

#### Build (Gradle) (https://github.com/ballerina-platform/ballerina-lang/issues/13569) - @pahans 
- [x] Test fixing hackathon 
- [x] fix tests misc/ballerina-to-swagger
- [x] fix tests ballerina-integration-test
- [ ] langserver-core
- [ ] Enabling code coverage tools
- [ ] Migrating API Docs build

#### Formatting (https://github.com/ballerina-platform/ballerina-lang/issues/13280) - @NipunaMarcus 
- [ ] finalize first draft of formatting guideline(https://github.com/ballerina-platform/ballerina-lang/issues/13862)
  - [x] Fix 1st review issues https://github.com/ballerina-platform/ballerina-lang/issues/13862#issuecomment-469574553
  - [ ] Fix 2nd review issues https://github.com/ballerina-platform/ballerina-lang/issues/13862#issuecomment-470408168
- [ ] publish the draft

#### Meetings
- [ ] API docs spec review
- [x] OpenAPI designer review
- [x] Function Collapse review
- [x] Formatting Guideline review
- [x] 2nd Review for the Formatting Guideline draft

**Comment by kaviththiranga** [comment]
Find the next sprint plan https://github.com/ballerina-platform/ballerina-lang/issues/14213
