### ISSUE TITLE
StdLib sprint - Week 11 - 2019 

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-lang#14183]
#### HTTP
- [x] #13912 Upgrade netty version
- [x] #14072 Finalise the pluggable LB design and implement initail version
- [x] #14380 [HTTP/2] Handle exhausted Stream Id for client
- [x] #10459 Implement support for OAuth2 client-credentials & password grant type for client authentication
- [x] #14041 Content type validation should be removed from request and response payload getter APIs

#### Scenario Test
- [x] #14251 Make test script work with TestNG based tests
- [x] Move to prod 
- [x] ballerina-platform/ballerina-scenario-tests#4 Finalize docs
- [x] Automate one HTTP BBG and move it to the prod.
- [x] Move Kafka BBG to TestGrid cont.

#### Data
~~- [ ] Evaluate and document MySQL features for revamping effort~~
- [x] ballerinax/jdbc#44 Sync ballerinax/jdbc with latest Ballerina changes

#### Socket
- [x] Improve UDP socket client test coverage
- [x] Add BBE for UDP socket client

#### SOAP
- [x] Propose a design for SOAP client

#### Messaging
- [x] NATS - Request/Response Pattern Implementation 
- [x] RabbitMQ - V2 Design
- [x] Artemis - Write integration test using embedded broker

#### Path 
- [x] V2 Design - Identify functions which have sys calls and make them under OS package
- [x] normalize() function
- [x] resolve() function
- [x] split() function

#### Time
- [x] Refactor Time API

#### Dependencies
- [x] #14305 Removing unused carbon dependancies from Ballerina

#### IO
- [x] Fix IO not appending the file issue.
