### ISSUE TITLE
Tooling Sprint - Week 11- 2019

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#14213]
#### API docs
- [ ] Create HTML designs of the pages - in progress
- [x] Add specs for construct pages

#### Reviews
- [ ] OpenAPI to Ballerina terminology mapping review
- [x] usability Issues review meeting

#### Lang Server
- [x] Design finalize, review and merge Goto Definition revamp - #14292
- [x] Fix language server gradle build test issues - Fixed with #14412 & #14407
- [ ] Compilation Unit Caching for Parser
- [x] Source Pruning Implementation phase 1

#### OpenAPI tools @DimalChandrasiri 
- [ ] BBG Update
- [ ] merge swagger -> openAPI rename PR
   - [x] - Build without test failures
   - [ ] - local pack testing - In progress
- [ ] draft OpenAPI tooling spec - In Progress

#### Diagram 
-  [Function Collapsing - In Progress](https://github.com/ballerina-platform/ballerina-lang/issues/13546) @roonyh 
   - [ ] Send update to public list
   - [x] Refactor AST visitors to allow instantiation
   - [ ] Handle invocations that cannot be collapsed (native code)
   - [x] Handle function invocations containing workers
   - [x] Handle function invocations containing endpoints

#### Idea Plugin - @NipunaRanasinghe - [Roadmap](https://github.com/ballerina-platform/ballerina-lang/issues/13991)
- [x] Publish to maven central
- [x] Find references support
- [ ] Hover support
- [x] Send update to public list

#### Build (Gradle) (https://github.com/ballerina-platform/ballerina-lang/issues/14337) - @pahans
-  [x] STDLib doc generation - replace docerina mvn plugin [#14319](https://github.com/ballerina-platform/ballerina-lang/pull/14319)
-  [x] Enabling code coverage tools [#14434](https://github.com/ballerina-platform/ballerina-lang/pull/14434)
-  [ ] compare gradle vs maven build packs
-  [x] break gradle build upon npm build failure
-  [ ] Configure gradle cache server

#### Formatting (https://github.com/ballerina-platform/ballerina-lang/issues/13280) - @NipunaMarcus
- [x] Fix default keyword test failure - https://github.com/ballerina-platform/ballerina-lang/pull/14390
- [ ] finalize first draft of formatting guideline(https://github.com/ballerina-platform/ballerina-lang/issues/13862)
  - [x] Fix 2nd review issues https://github.com/ballerina-platform/ballerina-lang/issues/13862#issuecomment-470408168
  - [x] Schedule 3rd review
  - [x] Fix 3rd review issues https://github.com/ballerina-platform/ballerina-lang/issues/13862#issuecomment-471859644
  - [x] Schedule 4th Review
  - [x] Fix 4th review issues https://github.com/ballerina-platform/ballerina-lang/issues/13862#issuecomment-472702006
  - [ ] Schedule 5th Review
  - [ ] Fix 5th review issues
- [ ] Share on public list for feedback

**Comment by kaviththiranga** [comment]
Closing in favor of https://github.com/ballerina-platform/ballerina-lang/issues/14423
