### ISSUE TITLE
Language sprint - Week 11 - 2019

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14212]
## 2019r1 Spec deviations.

- [ ]    #13849 Variable Mutability in Closures.
- [x]    #13838, #13804: Improvements to finite types & is check not allowed for union types that have an intersection. PR #13931
- [ ]    #13899: Add map literal support to constants.
- [ ]    #13342 Object __init() methods return should be a subtype of error|(). PR #14220
- [ ]    #13946 XML Expression Improvements for 0.990.0 Spec
- [ ]    #13821: Ballerina byte type needs to be refactored to use the long registry and needs to be treated similarly to int. PR: #14209
- [ ]    #13865: Arithmetic operations on byte type need to be supported. PR: #14209
- [ ]    #14012 : default' is used to define the default worker in a function so it should be treated as a keyword. PR:  https://github.com/ballerina-platform/ballerina-lang/pull/14390
- [x]    #13583 Support const in static match statements
- [x]    #14067 Support expressions in record index based access
- [x]    #14065 Support type cast with errors
- [x]    #13655 Invalid result on is check as user defined error type
- [x]    #13230 Inherent type violating updates allowed in type-widening contexts for tuples
- [ ]    #13171 The detail mapping value of an error type should be a frozen value
- [x]    #13900 Forward reference reordering needs to support Services and Objects PR #13920
- [ ]    #14255 Assigning a hex floating point number to decimal results in a bad, sad error. PR: #14401 
- [ ]    #13168 Support `0.` syntax for floating point literals - Differed.   
- [ ]    #14398 Support positively signed literal assignment to decimal type. PR: #14401
- [ ]    #14113 Update the syntax for closed records. PR #14315
- [ ]    #13231 (anydata|error)[] and map<anydata|error> need to be considered as anydata
- [ ]    #13205 Detail type descriptor of Error type descriptor should be sub type of map<anydata|error>
- [ ]    #13181 Default record rest field type should be anydata|error (pure) 
- [ ]    #14248 Error type definitions allowed with non-string reasons
- [ ]    #14328 Ignoring values of expressions. (checkpanic expr and restrict ignoring error type)

## Compiler - Bug and Improvements.
- [ ]    #14296 Allow array var definitions for types which don't have implicit init values. PR #14359 

## Streaming
- [ ]    Prioritize the pattern processors based on their importance.
- [ ]    Design the very basic pattern processor (The basic state machine)
- [ ]    #14037 Come up with a different approach to receive events into streams instead of using MB topics
- [x]    #14035 Write a walk-thru/tutorial like blog on implementing a custom window
- [x]    #14126 Intermittent failure - BallerinaStreamsV2TimeLengthWindowTest.testTimeLengthQuery1
- [x]    #14200 Streams tests are not working in the gradle build
- [x]    #14256 Improve doc comments in streaming module

## Language extensions (k8s, docker etc.)

- [x]    ballerinax/kubernetes#297 Support Kubernetes ConfigMaps in main Functions
- [x]    ballerinax/kubernetes#299 Use Snowdrop's Istio Models for generating Istio Artifacts.
- [ ]    ballerinax/kubernetes#293 Deploy a ballerina service with one command
- [ ]    ballerinax/docker#198 Make ballerina docker image official

## Gradle Migration

- [x]  Testerina. PR #14178
- [x]  Spec conformance tests. PR #14178
- [x] Unit tests always rebuild instead of using the cached previous build. PR #14278

## Tools - Packerina and Tests

- [x]  ballerina-platform/ballerina-lang#14241 Allow giving to give an environment variable for Ballerina Central access token
- [x]  ballerina-platform/ballerina-lang#13918 Test that searches for a module in Ballerina Central fails intermittently
- [x]  ballerina-platform/ballerina-lang#14079 Ballerina init command is not working properly on Desktop
- [x]  ballerina-platform/ballerina-lang#13898 Intermittent failure - ballerina-examples/fork-variable-access. PR https://github.com/ballerina-platform/ballerina-lang/pull/14320
- [x] #13975, #14125 PkgRunFunctionPositiveTestCase intermittent failures. PR #14247
