### ISSUE TITLE
Migrate build to gradle

### ISSUE THREAD

**Issue by pahans** [ballerina-platform/ballerina-lang#14337]
[Gradle migration Doc](https://docs.google.com/spreadsheets/d/1fwkpkg7iZwvdnfuxdhyj8QcX0N651QfRsAnDP6rU9dA/edit#gid=0)
**Migrate tooling modules** 
- [x] Migrate docerina maven module to gradle [#14319](https://github.com/ballerina-platform/ballerina-lang/pull/14319)
- [x] Composer modules [7dbb848](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/7dbb8484772ec26ff4133f1216d38dda59527aa0)
- [x] Cache npm build and node_modules tasks [d8f3481](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/d8f3481093d2dfc568fc45bc21e64b9ea117223f)
- [x] VSCode extension [d8f3481](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/d8f3481093d2dfc568fc45bc21e64b9ea117223f)
- [x] Ballerina to swagger
- [x] Fix Language server dependency issues [4e374ad](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/31455f2b6147763fbecff84128489229e6d2257e)
- [x] Add language server jars to tools distribution
- [x] Fix ballerina -v command [931c9a7](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/931c9a7c6e2e172f29490beb5eeaa9bd4e3ecbe8)
- [x] Cache outputs of composer library [dac6f65](https://github.com/ballerina-platform/ballerina-lang/pull/14021/commits/dac6f65898cf68934da47762c8fbbb6fcdf8ae3a)
- [x] Fix windows npm command issues [a42b34f](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/a42b34fbf9586fcf200f55c4a9e54ca9432adacf)
-  [x] Enabling code coverage tools
-  [x] Compare gradle vs maven build packs
-  [x] Break gradle build upon npm build failure [#14372](https://github.com/ballerina-platform/ballerina-lang/pull/14372)

**Fix test failures**

- [x] stdlib/runtime
- [x] misc/ballerina-to-swagger
- [x] stdlib/grpc
- [x] docerina
- [x] langserver-core [#14331](https://github.com/ballerina-platform/ballerina-lang/issues/14331) [#14412](https://github.com/ballerina-platform/ballerina-lang/pull/14412)
- [x] testerina
- [x] ballerina-integration-test
- [x] stdlib/http
- [x] ballerina-unit-test
- [x] spec-conformance-test

**Gradle**
- [x] Enable fast finish in travis build [#14085](https://github.com/ballerina-platform/ballerina-lang/pull/14085)
- [x] Migrate mvn annotation processor to gradle [#13914](https://github.com/ballerina-platform/ballerina-lang/pull/13914)
- [x] Sync up gradle branch with master [#14021](https://github.com/ballerina-platform/ballerina-lang/pull/14021), [
9c6e86d](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/255bebe29d7ed36d828981a74469b2faf54199e7), [255bebe](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/255bebe29d7ed36d828981a74469b2faf54199e7)
- [x] Run maven and gradle in parallel jobs [#14021](https://github.com/ballerina-platform/ballerina-lang/pull/14021)
- [x] Enable build scans [#14021](https://github.com/ballerina-platform/ballerina-lang/pull/14021)
Reduce travis logs in maven build to prevent travis hitting 4MB log file limit [6010a19](https://github.com/ballerina-platform/ballerina-lang/pull/14021/commits/6010a1962f6e2bc360ef0785e6210528263d38ba)
- [x] Add testng configs [d045b94](https://github.com/ballerina-platform/ballerina-lang/pull/13914/commits/d045b94da52a690fc5e8aedd505f8fc863f48171)
- [x] Move hard coded version numbers to a config file
- [x] Fix issue, debugging hangs 'balo' projects in Intelij IDEA
- [x] Fix issue, spot bugs tasks not caching for balo projects.
- [x] fix ballerina push/pull commands
- [x] ballerina examples tests
- [x] compare packs maven and gradle
- [x] enable testng configs for all modules
- [x] Release process tasks [#14378](https://github.com/ballerina-platform/ballerina-lang/issues/14378)
- [x] Generate Java docs
