### ISSUE TITLE
Implement new Annotation syntax

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14352]
Coppied from the spec 2019r1

annots := annotation*
annotation := @ annot-tag-reference annot-value

Annotations provide structured metadata about a particular construct. Multiple annotations can be applied to a single construct. An annotation consists of a tag and a value.

annotation-decl :=
   metadata
   [public] [const] annotation [type-descriptor] annot-tag 
   [on annot-attach-points]
annot-tag := identifier
 
An annotation-decl declares an annotation tag. The type-descriptor specifies the type of the annotation tag. The type must be a subtype of one of the following three types: true, map<anydata>, map<anydata>[]. If the type-descriptor is omitted, then the type is true.

annot-tag-reference := qualified-identifier
annot-value := [mapping-constructor-expr]

An annot-tag-reference in an annotation must refer to an annot-tag declared in an annotation declaration. If the annotation includes a mapping-constructor-expr, then the value of the annotation is the mapping value resulting from evaluating the mapping-constructor-expr; otherwise the value is the boolean value true.

For every construct that has an annotation with a particular tag, there is an effective value for that annotation tag, which is constructed from all the annotations with that tag that were attached to that construct. The effective value belongs to the type of the annotation tag.

The type of the annotation tag constrains both the annotation value and the occurrence of multiple annotations with the same tag on a single construct as follows.
If the type of the annotation tag is T[] for some T, then the mapping-constructor-expr must be specified and its static type must be a subtype of T; multiple annotations are allowed; the effective value is a list of all annotations with the tag in the order specified.
Otherwise, multiple annotations with this tag are not allowed and the effective value for the tag is the value of the single annotation with the tag.
If the type of the annotation tag is true, then the mapping-constructor-expr must not be specified.
Otherwise, the mapping-constructor-expr must be specified and its static type must be a subtype of the type of the annotation tag.

If the annotation-decl for a tag specifies const, then a mapping-constructor-expr in annotations with that tag must be a const-expr and is evaluated at compile-time with the semantics of a const-expr. Otherwise, the mapping-constructor-expr is evaluated when the annotation is evaluated and the resulting value is automatically frozen.

An annotations applied to a module-level declaration is evaluated when the module is initialized. An annotation applied to a service constructor is evaluated when the service constructor is evaluated. An annotation occurring within a type descriptor in a block is evaluated when the type descriptor is resolved.

annot-attach-points := annot-attach-point (, annot-attach-point)*
annot-attach-point :=
   dual-attach-point
   | source-only-attach-point
dual-attach-point := [source] dual-attach-point-ident
dual-attach-point-ident :=
   type
   | object
   | [object|resource] function
   | parameter
   | return
   | service
   | listener
source-only-attach-point := source source-only-attach-point-ident
source-only-attach-point-ident :=
   annotation
   | extern
   | var

The annot-attach-points specify the constructs to which an annotation can be attached.

When an attachment point is prefixed with source, then the annotation is attached to a fragment of the source rather than to any runtime value, and thus is not available at runtime. If any of the attachment points specify source, the annotation-decl must specify const.

**Comment by hasithaa** [comment]
Initial implementation added with https://github.com/ballerina-platform/ballerina-lang/pull/15884.  
@MaryamZi Please add remaining tasks.

**Comment by MaryamZi** [comment]
The following are the remaining tasks for the annotation change.

Deviations
- [ ] Not all annotation attach points are supported - https://github.com/ballerina-platform/ballerina-lang/issues/18207
- [ ] Restrict constraints of maps/fields of records to be anydata and make the values immutable - https://github.com/ballerina-platform/ballerina-lang/issues/15533 (Related issue - https://github.com/ballerina-platform/ballerina-spec/issues/70)

Tasks
- [ ] Add annotation attachments to BIR - #16379
- [ ] Add a BBE for annotations and annotation access - #16161
- [ ] Add tests for service reordering due to annotations - #16555
- [ ] Re-enable annotation balo tests - #17999

Bugs
- [ ] Bad, Sad error when using `typeof` inline with annotation access - #17936

**Comment by hasithaa** [comment]
Closing this issue, since limitations are captured as separate issues.
