### ISSUE TITLE
StdLib sprint - Week 12 - 2019

### ISSUE THREAD

**Issue by VijithaEkanayake** [ballerina-platform/ballerina-lang#14389]
#### HTTP
- [x] #14301 TPS is lower in HTTP/2 server downgrade scenario compared to HTTP/1.1
- [x] #13705 TPS is lower in HTTP/2 than HTTP/1.1 for passthrough scenario 
- [x] #13525 Improve OAuth2 support for revoking refresh token for client authentication
- [x] #10468 Tokens keep getting refreshed when OAuth2 client-id is shared across multiple HTTP clients
- [x] #14249 A memory leak warning occurred while load testing data-binding
- [x] #13658 Intermittent test failure - NonBlockingListenerActionTest.testServiceAvailabilityCheck
- [x] #14472 Add support for prior knowledge in transport test backend and enable relevant tests
- [x] #13495 Intermittent test failure - AESCipherToolNegativeTest.testEncryptionAndDecryptionWithTwoCipherTools

#### Scenario Test
- [x] Move Kafka BBG to TestGrid
- [x] #14533 Move scenario test code to ballerina-platform/ballerina-scenario-tests repository, test on dev and move to prod
- [x] #14535 Apply identified best practices to TestGrid scripts
- [x] Do the KT on BBG onboarding to the team
- [x] ballerina-platform/ballerina-scenario-tests#9 Fix namespace cleanup issues
- [x] ballerina-platform/ballerina-scenario-tests#10 Improve error handling in deployment setup script

#### Data
- [x] Read up on H2, check H2 depenedencies in components and see whether H2 cannot be moved out

#### Gradle Build fix
- [x] Fix Socket module
- [x] Fix Cache module
- [x] Fix File module
- [x] Fix Crypto module
- [x] Fix MIME module
- [x] Fix Encoding module
- [x] Fix Config API module
- [x] Fix Internal module
- [x] #14582  Fix gradle build issues in H2 module
- [x] Fix WebSub module

#### Messaging
- [x] NATS - Reflecting the changes in V2 design
- [x] NATS - Request/Response Pattern 
- [x] Fix https://github.com/ballerina-platform/ballerina-lang/issues/13338
- [x] RabbitMQ - Refactor implementation 

#### SOAP
- [x] Propose a design for SOAP client.

#### Path 
- [x] Test Path API implementation in windows and fix failing testcases(50% completed, task continued to next sprint)

#### Performance
- [x] APIM

**Comment by daneshk** [comment]
All the tasks are completed, Hence closing Sprint - Week 12.
