### ISSUE TITLE
Language sprint - Week 12 - 2019

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#14568]
## 2019r1 Spec deviations.

- [ ]    #13849 Variable Mutability in Closures.
- [ ]    #13899: Add map literal support to constants. PR #14185
- [ ]    #13342 Object __init() methods return should be a subtype of error|(). PR #14220
- [ ]    #13946 XML Expression Improvements for 0.990.0 Spec
- [x]    #13821: Ballerina byte type needs to be refactored to use the long registry and needs to be treated similarly to int. PR: #14209
- [x]    #13865: Arithmetic operations on byte type need to be supported. PR: #14209
- [ ]    #14012 : default' is used to define the default worker in a function so it should be treated as a keyword. PR:  https://github.com/ballerina-platform/ballerina-lang/pull/14655
- [ ]    #13171 The detail mapping value of an error type should be a frozen value
- [ ]    #14255 Assigning a hex floating point number to decimal results in a bad, sad error. PR: #14401 
- [ ]    #13168 Support `0.` syntax for floating point literals - Differed.   
- [ ]    #14398 Support positively signed literal assignment to decimal type. PR: #14401
- [ ]    #14113 Update the syntax for closed records. PR #14315
- [ ]    #13231 (anydata|error)[] and map<anydata|error> need to be considered as anydata
- [ ]    #13205 Detail type descriptor of Error type descriptor should be sub type of map<anydata|error>
- [ ]    #13181 Default record rest field type should be anydata|error (pure) 
- [ ]    #14248 Error type definitions allowed with non-string reasons
- [ ]    #14376 int/float literal assignability does not work as expected for union types
- [x]    #14596 Extern functions need to be defined as `= external` instead of `extern function`
- [x]    #14328 Ignoring values of expressions. (checkpanic expr and restrict ignoring error type)

## Compiler - Bug and Improvements.
- [ ]    #14296 Allow array var definitions for types which don't have implicit init values. PR #14359 
- [ ]    #14379 Invalid types with int/float literal assignment to finite type
- [ ]    #14405 Casting a finite type to a finite type is not allowed even when there is an intersection in value spaces

## Streaming
- [ ]    Prioritize the pattern processors based on their importance.
- [ ]    Design the very basic pattern processor (The basic state machine)
- [x]    #14037 Come up with a different approach to receive events into streams instead of using MB topics
- [ ]  #14387 count() and distinctCount() in streams do not work when passed into a function
- [x]  #14385 Public streams in another module cannot be directly accessed
- [x]  #14383 The streams initialized inside a function are not working
## Language extensions (k8s, docker etc.)

- [ ]    ballerinax/kubernetes#293 Deploy a ballerina service with one command
- [ ]    ballerinax/docker#198 Make ballerina docker image official

## Tools - Packerina and Tests
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/14276 Ballerina Push Should End with Error Exit Code (1) When Artifact Already Exists
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/14285 Need to revisit the integration tests written to test interactions with Ballerina Central

**Comment by hasithaa** [comment]
Guys, Please add tasks here. @gimantha @grainier @pubudu538 @MaryamZi @Anoukh @Shan1024 @pranavan15 @rdhananjaya @hemikak @NatashaWso2 @sameerajayasoma
