### ISSUE TITLE
StdLib sprint - Week 13 - 2019

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-lang#14588]
#### HTTP
- [x] Study HTTP/2 flow control principals and netty implementation of that
- [x] Verify OAuth2 client authentication
- [x] Discuss on Authn and Authz filters, handlers engagement

#### GRPC
- [x] #14494 UnaryBlockingBasicTestCase.testNonBlockingBallerinaClient fails 
- [x] #14640 Intermittent failure - ballerina-examples/grpc-server-streaming

#### Message Transformation
- [x]  Implement XSLT support
- [x]  Add test cases

#### Scenario Test
- [x] Add Kafka BBG in TestGrid dev environment. 
- [x] Add Kafka BBG in TestGrid production environment.

#### Data
- [x] Identify the tests/grouping to be added on TestGrid for each database
- [x] Figure out a way to parameterize the tests so that same set of tests can be run on all databases
- [ ] Implement the tests on TestGrid

#### Messaging
- [x] NATS durable subscription
- [x] Implement Artemis compiler plugin
- [x] Implement JMS compiler plugin
- [x] Add examples for Artemis connector

#### SOAP
- [x] Fix issues in existing SOAP client connector. https://github.com/wso2-ballerina/module-soap/issues
- [x] Finalize the design of the SOAP connector revamp.
- [x] Identify the common SOAP use cases in the production environment.
- [x] Study usernameToken Password digest ws-security and ways to implement it from Ballerina.

#### Task
- [x] Update documentation and fix intermittent test failures

#### Path 
- [x]  Test Path API implementation in windows and fix failing testcases ctd

**Comment by chamil321** [comment]
Next week sprint : https://github.com/ballerina-platform/ballerina-lang/issues/14749
