### ISSUE TITLE
Tooling Sprint - Week 13- 2019

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#14691]
#### Diagram
- [ ] support for endpoints anywhere in the body - #14479
- [ ] Support for adding invocations for client object methods via diagram - #9815
- [ ] Fix worker interaction rendering - #14589

#### IntelliJ Plugin - #13991
- [x] Language Client
  - [x] Repository Migration to Ballerina-Platform
- [x] Update plugin with the 0.990.4 grammar support
- [x] Bug Fixes

#### API Doc Generator - #13548
- [ ] design handlebar templates for initial [spec](https://docs.google.com/document/d/1eyiduNRrUtqoL_e9AksM8B3ClRW0T-RzTrH_qwJZZjU/edit?usp=sharing) - in progress

**Comment by kaviththiranga** [comment]
Closing in favor of https://github.com/ballerina-platform/ballerina-lang/issues/14423
