### ISSUE TITLE
Tooling Sprint - Week 15- 2019

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#14959]
#### API Doc Gen
- [x] Share initial designs with the team
- [ ] Complete doc design structure

#### Lang Server
- [x] [Implement Token Removal strategy for Source Prune](https://github.com/ballerina-platform/ballerina-lang/issues/14216)
- [x] [Introduce meaningful sub types to BType category in suggestions](https://github.com/ballerina-platform/ballerina-lang/issues/13621)
- [x] Bug Fixes

#### IntelliJ Plugin
- [x] Language Client
  - [x] Workspace Symbols Support
  - [x] Add support for resetting a failed or timed out language server
  - [x] Add support for file name patterns for server registration
  - [x] [Bug fixes](https://github.com/ballerina-platform/lsp4intellij/pull/42)
- [ ] Update Langserver.org with Lsp4IntelliJ client details

#### Formatting 
- [ ] Review formatting guideline and finalize (https://github.com/ballerina-platform/ballerina-lang/issues/14864)
  - [x] 1st Review pre-finalizing
  - [x] Fix requested changes - https://github.com/ballerina-platform/ballerina-lang/issues/14864#issuecomment-482219139
  - [ ] Finalizing review
- [x] Fix union type optional model change - https://github.com/pubudu91/ballerina/pull/9
- [x] Fix formatting related to sealed records https://github.com/pubudu91/ballerina/tree/fix-14748
- [x] Fix gaps between formatting tool and the guidelines
  - [x] Fix Import sorting
  - [x] Fix record literal expanding on demand
- [ ] CLI tool for formatting
- [x] Add more support for syntaxes 

#### OpenAPI tooling
- [x] Json Schema to Ballerina Type and Validation Mapping Spec
  - [x] dicussion on how to map ballerina types with json schema types
  - [x] Finalizing Review

**Comment by kaviththiranga** [comment]
Closing the sprint ticket and will create a new one for the current week.
