### ISSUE TITLE
Tooling Sprint Week 19

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#15277]
## API Docs
- [ ] Send to public group

## IntelliJ Plugin
- [x] Diagram viewer 
  - [x] Fix font rendering
  - [x] Add firebug support for diagram view
  - [ ] Fix go-to-source from diagram

## Formatting & Linter
- [ ] Figure out fixing missing whitespaces for XML, Pattern Clause, Stream
- [ ] Spec improvements
- [x] Match formatter implementation to guide - fix gaps
- [ ] CLI command for formatter 
- [ ] Add support for syntaxes
  - [x] forkjoin - https://github.com/ballerina-platform/ballerina-lang/pull/15328
  - [ ] type desc

## Diagram Verifications Test
- [ ] BBEs & BBGs

## Lang-Server
- [x] Source prune Review & Merge
- [ ] [Quick fix for taint and untaint status changes diagnostics](https://github.com/ballerina-platform/ballerina-lang/issues/14907)
- [x] [Code action to fix return type signature](https://github.com/ballerina-platform/ballerina-lang/issues/13509)

## JDK path Fix
- [ ] verify the packs using build pipeline
- [x] merge ballerina-platform/ballerina-distribution#137

## Debugger
- [ ] DAP - Server Side
   - [x] Server launcher
   - [x] json-rpc connection
   - [x] Threads request
   - [x] Stacks request
- [ ] Review on Wednesday
- [ ] DAP Client for IDEA
- [ ] search existing options

## Open API
- [x]  review meeting Proposal 2
- [ ] bug fixes on existing API designer

## Theia
- [x] Verify theia fixes

**Comment by kaviththiranga** [comment]
closing and moving to https://github.com/ballerina-platform/ballerina-lang/issues/15333
