### ISSUE TITLE
StdLib sprint - Week 20 - 2019/05/13 to 2019/05/17

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#15285]
Previous week #15195

#### HTTP
- [x] Fix eventloop task execution order in local flow controller
- [x] Perform load tests in test set up with HTTP/2 flow control  change 
- [x] #15324 Http/2 upgrade scenario doesn't work when the request has a payload
- [x] Implement OAuth2 inbound authentication
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/14953 Provide first class support for essential request and response properties in carbon message

#### Data
- Write Select tests for PostgreSQL
     - [x] Write SQL Scripts
     - [x] Write tests
- Write Batch update tests for PostgreSQL
     - [x] Write SQL Scripts

#### Scenario Tests
- [x] Create separate jobs for RC and SNAPSHOT tests for BBG TestGrid jobs - Amend the scripts to automatically fetch the current snapshot(nightly) version. 

#### Messaging
- [x] Add support for manual client acknowledgements in RabbitMQ Connector
- [x] Complete data binding support for Artemis connector along with compiler plugin support and tests
- [x] Fix an issue in the WebSocket data binding implementation

#### JBal Migration
- [x] HTTP/MIME/IO compilation

#### Test Fixes
- [x] Reduce windows test failures - #15216
