### ISSUE TITLE
StdLib sprint - Week 22 - 2019/05/27 to 2019/05/31

### ISSUE THREAD

**Issue by Manuri** [ballerina-platform/ballerina-lang#15419]
Previous week #15361

#### HTTP
- [x] #15379 Fix sender configuration issue in http clients
- [x] #15360 Separate HTTP/1 settings from HTTP/2 settings in ClientEndpointConfig
- [x] Adding HTTP/2 resiliency integration tests
- [x] Design HTTP error revamping

#### Security
- [x] #15385 Update Module Structure for Ballerina Inbound Authentication

#### Data
- Write PostgreSQL call tests 
    - [x] Write tests
- [x] Write scripts required to get the tests running on TestGrid
- [x] Get the tests running on dev

#### Messaging
- [x] RabbitMQ Client Acknowledgements and QoS Settings
- [x] [JMS] Rename Receiver/Subscriber to Listener
- [x] Propose new design for JMS Message
- [x] Write scenario for test grid in Artemis

#### Websocket
- [x] Fix BallerinaException propagating to the transport layer and remove unused returns

#### JBal Migration
- [x] StdLib compilation and test enabling
