### ISSUE TITLE
StdLib sprint - Week 23 - 2019/06/03 to 2019/06/07

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-lang#15490]
Previous week #15419 

#### HTTP
- [x] #15519 When the server is down, a call made to that service hangs 'clientEP->submit'
- [x] Design and refactor HTTP outbound authentication with custom provider engagement
- [x] Design error types for HTTP secure client specific errors
- [x] Design error types for HTTP failover client specific errors
- [x] HTTP client enabling

#### Data
- [x] Make DB Connections non-blocking - Implementation
- [x] Add the job to prod

#### Messaging
- [x] Add transaction support for RabbitMQ Connector
- [x] Add scenario test for Artemis to Test grid
- [x] Move JMS module to jballerina Repository - Preparation

#### gRPC
- [x] #13409 Add observability support for gRPC
- [x] #15130 Files generated during gRPC integration tests are not cleaned up afterwards
- [x] #15257 Generated proto contract is not correct when check exp is used in send statement
