### ISSUE TITLE
Tooling Sprint - Week 26

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#15917]
**Lang Changes**
https://github.com/ballerina-platform/ballerina-lang/issues/16012

### Lang Server
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/15882
- [x] [Signature Help Revamp](https://github.com/ballerina-platform/ballerina-lang/pull/15874)
    - [x] Add support for 'new' constructor
    - [x] Add support for chain completed function invocations
    - [x] Trigger signatureHelp on completions for function invocations
    - [x] Test signatureHelp for functions in stdlibs
- [x] Diagnostic support for full project (#15971)
- [x] Revamp Hover Provider (#15971)
- [x] Bug Fixes (#15971)

- [ ] [Code Actions for add/remove 'abstract' keyword](https://github.com/ballerina-platform/ballerina-lang/issues/16010) 

### Diagram
- [x] Index page styling - @srsharon 
- [x] team demo
- [ ] merge to jballerina branch

### IntelliJ Plugin
- [x] Language Client
  - [x] Add Signature Help Support
- [x] Debugger
  - [x] Initialize
  - [x] Set Breakpoints
  - [x] Attach

### Open API
- [ ] Type Mapping - code review - mid week
   - [x] Type extraction from OpenApi Document
   - [] Template generation from the extracted types
      `Current progress : Currently the type matching iteration is implemented to match with the types available for the example petstore provided by the openapi. With the extracted types, the templating of the ballerina service is still under development.`
- validator plugin https://github.com/ballerina-platform/ballerina-lang/issues/15800
  - [x] path params validations
  - [x] Filtering using tag and operations

### Debugger
- [ ] switch to ```ballerina run```
- [ ] quick hackathon to fix variable resolving

### Formatting
- Publish style guide to ballerina.io - ONHOLD (till the site revamp)
- Add formatter tool to the ballerina.io - ONHOLD (till the site revamp)
- [ ] Fix issues
  - [ ] Formatting comments
  - [ ] ForkJoin formatting
  - [ ] inline listener formatting
  - [x] Worker sync send - https://github.com/ballerina-platform/ballerina-lang/pull/15977
  - [x] Worker Flush - https://github.com/ballerina-platform/ballerina-lang/pull/15977
  - [x] Unary expr formatting - https://github.com/ballerina-platform/ballerina-lang/pull/15943
  - [x] Additional scenario for check - https://github.com/ballerina-platform/ballerina-lang/pull/15935/commits/9e0cc4262912db736bfc1a6b8c768cb57698a8f4

**Comment by kaviththiranga** [comment]
Moving to https://github.com/ballerina-platform/ballerina-lang/issues/16089
