### ISSUE TITLE
Generic way to support identifiers in file/module/variable names

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-lang#19478]
**Description:**
Currently there are different ways that characters such as "." and "$" are handled when generating the java class files or variable names. Some characters for identifiers are not yet supported also with jvm code generation. We need a generic way to support all the identifiers in ballerina at runtime and generated code as-well.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by SupunS** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/18158

**Comment by HindujaB** [comment]
This is the progress of quoted identifier implementation

**Task list**

- [x] Encoding, Decoding schemes
- [x] Variables
  - [x] Constants, Final, Global variables
  - [x] Local variables
- [x] Functions 
  - [x] Function names
  - [x] argument names
- [x] Structured type (including fields, attached functions)
  - [x] Records
  - [x] Objects 
    - [x] client objects
- [x]  workers 
   - [x] worker interaction
- [ ] Service
  - [x] Service Name
  - [ ] Resource functions
- [ ] Decoding for runtime invocation (eg. toString(), member access)
