### ISSUE TITLE
Improve function-type-descriptor validation

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#19553]
This issue is created to track all improvements related to `function-type-decriptor` validation in the compiler. 

Issues : 

- [x] #18979 Can't invoke a global function pointer defined using var
- [x] #19538 Rest parameter doesn't work as expected with function pointers
- [x] #18710 Function pointer invocations are special cased when type checking the invocation expression
- [ ] #19542 Default values do not work with function pointers

**Comment by irshadnilam** [comment]
Related
https://github.com/ballerina-platform/ballerina-lang/issues/10639

**Comment by hasithaa** [comment]
Resolving this issue. The only remaining part is  Default values do not work with function pointers which is captured here. https://github.com/ballerina-platform/ballerina-lang/issues/10639
