### ISSUE TITLE
Ballerina Tooling - Week 44

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-lang#19563]
- Playground - https://docs.google.com/document/d/1lSKUZAKkbs2IKVJDDWzth8gtm48jgD3Xkw2QePoHXhI/edit
   - [ ] compiler api - finish implementation
   - [ ]  initial preview EOW 44
             - [X] Deploy to play.ballerina.io

- Intellij Plugin
  - [x] Bug fixing
    - [x] Remove multi-line string support and add smart text splitting - #19058
    - [x] Fix and improve double quotes handling - #19234
  - [ ] Language client  
    - [x] Revamp request manager Implementation
    - [ ] Snippet support
    - [ ] Revamp existing server definition implementation to clean up unused server definition types - [#110](https://github.com/ballerina-platform/lsp4intellij/issues/110) 
    - [ ] Add a new server definition type to register language server definitions using process builder instances - [#110](https://github.com/ballerina-platform/lsp4intellij/issues/110)

- Diagram
  - [ ] @DimalChandrasiri fix issue #19168
  - [ ] Commit guide md inside diagram module

- Smart Syntax Highlighter
  - [ ] LS extended API - complete highlighting unused variables
  - [x] next-week - create an spec on which constructs to highlight (eg: endpoints, etc)

- Highlighting Grammar
   - [ ] KT on grammar internals

- Code coverage
  - [x] Follow up on Testerina Executable jar & finalize alternative
  - [x] Update dev group on status

- LS & Debugger Launcher scripts revamp
  - [x] Implement CLI command for LS and Debug Adapter
  - [ ] Modify IntelliJ Plugin to work with CLI command
  - [x] Modify VSCode plugin to work with CLI command
  - [ ] Test functionality and backward compatibility across {new, old} Plugin and {new, old} SDKs in Windows10, Windows8, Ubuntu18.04, Mac
- Debugger
  - [ ] KT with @pahans
  - [ ] Fix an issue to get in-touch 
  - [ ] Follow up on global variable support

- Language Server
   - [x] Finish Spec conformance check
   - [ ] Signature Help
   - [x] GoToDef - follow up with Dhananjay on Identifier position
             - Define scope of support
   - [x] Follow up on compiler improvements for existing compiler

- OpenAPI
  - [x] Fix schema generation for nested types
            - [ ] Add test cases
  - [ ] Work on adding more tests

- OpenAPI Validator
  - [x] Revamp the OpenAPI Messages and update the spec.
  - [x] Revamp OpenAPI Validator plugin code.
  - [ ] POC code action for validation message.

- Linter 
  - [x] Work with compiler team and add capture WS flag
  - Add linter as a subtask to build command (+ a flag to disable/enable)
    -  [x] Initiate a thread on dev group approach
  - [x] Sync up with master

- Formatter
   - [x] Improve Code coverage and refactor the code to remove old code impl - current code coverage is 89%
   - [ ] Fix issues in Line breaking 
   - [ ] Plan for a team wide hackathon to fix formatting in samples
   - [ ] Update style guide with naming conventions
