### ISSUE TITLE
Implement new XML support

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#19570]
This issue create to track implementation progress of new [proposed XML](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md) design https://github.com/ballerina-platform/ballerina-spec/issues/288 

Rough Implementation Direction, 

**Compiler front end**
- Current Java-based version - No changes required. We already create AST nodes for the XML literal expression using the ANTLR-generated lexer and the parser. 
- New compiler front end (will be written in Ballerina). We will write the scanner and the parser bits that identify and create AST nodes for the XML literal expression. 

**Ballerina compiler JVM back end**
- We are using Axiom at the moment here now. To implement the runtime support for the new XML spec, we will replace Axiom with a custom XML tree with a customer tree builder written on top of StAX. Since this is JVM runtime, we will have to use Java here.  

**Ballerina compiler LLVM back end**
- We are not yet clear about this implementation. But, most probably, we will have to implement the XML runtime support in C++ or Rust.

Related issues

- [ ] #14261 Not all charactors allowed from XML spec as nameChar are not supported in Ballerina grammer
- [x] #18875 XML access expressions are not defined in the 2019R3 Spec 
- [x] #19384 XML namespace declarations should be in scope only in the source part in which they occur, as with import declarations. 
- [x] #18870 `ballerina/lang.xml` module contains functions not defined in the spec 

Sub tasks 

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/19910 Implement Table to XML convertion/datasource
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/19941 Implement/fix JSON to XML converter
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/19944 Enable disabled test case XMLSecurityTest
- [x] #19947 Add test cases to cover xml value equalancy 
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/20064 Migrate XML tests to use JVM values instead of BVM values.
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/20666 Implement langlib.xml functions to support new xml proposal
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/20667 Implement new XML navigation syntax 
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/20670 Validate xml atttribute names and element names to be within allowed charactors acording to w3 xml 
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/20879 Align XML attibute access with the XML proposal
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/20880 Add XML element name expression
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/21102 XML attribute access is Lax

- [x] https://github.com/ballerina-platform/ballerina-lang/issues/21129 Implement cycle detection in XML

After 1.2.0

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/22136 Method invocations in XML step expressions are not aligned with the spec

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/22135 XML iterator need to be update to return xml

- [x] https://github.com/ballerina-platform/ballerina-lang/issues/22069 Support XML sequence constraint type

- [x] https://github.com/ballerina-platform/ballerina-lang/issues/22053 XML index access using string index should be deprecated 

- [x] https://github.com/ballerina-platform/ballerina-lang/issues/22155 XML literal should be able to directly declare XML named subtypes

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/22151 Remove dependency on Axiom library as Ballerina xml no longer depend on it

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/24562 XML iterator still returns `xml|string` this should be just `xml`

**Comment by hasithaa** [comment]
Closing this issue, since XML support has been added and, remaining individual tasks are captured in separate issues.
