### ISSUE TITLE
Optimize the jballerina runtime

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#19653]
**Description:**

This issue is to keep track of all jballerina runtime performance improvement related tasks.

Optimizations can be done in four levels:
- [ ] Optimize BIR(#19709)
    - [x] Improve BIR emitter(#19706)
    - [x] Identify and do possible optimization (#19709)
    - [ ] Remove unwanted BBs (#20249)
- [x] Optimize byte code generation - Revisit the way we generate the byte code from BIR, and check for any possible improvements
    - [x] ~~Parallelize the function generation (#19704)~~
    - [x] Parallelize the class generation (#19934)
- [ ] Optimize the byte-code after generation
- [ ] Optimize runtime classes
    - [x] Profile and optimize http service flow.
    - [ ] Optimize value creation and operations on top of different values (eg: operation such as get, set, iterations) for each type.
        - [x] Records (#19654)
        - [x] Arrays (#19702)
        - [ ] Objects
   - [ ] Optimizing runtime type checking (#19028)

**Comment by SupunS** [comment]
HTTP flow was profiled and optimized by the PR https://github.com/ballerina-platform/ballerina-lang/pull/19603.

Now its the netty related classes and methods are the limiting factors

**Comment by warunalakshitha** [comment]
We have done the identified optimizations and I will close this.
