### ISSUE TITLE
HTTP - Cookie APIs implementation 

### ISSUE THREAD

**Issue by Tharuja** [ballerina-platform/ballerina-lang#19796]
**Description:**
Implemented Tasks:
- [x] Server can get cookies if available in the request.
- [x] Server can create and add valid cookies to the response (in "Set-Cookie" header).
- [x] Client can configure to enable/disable cookies, enable/disable persistent cookies and whether to block/unblock third party cookies.
- [x] Cookies in the inbound response are retrieved and added to the client's cookie store according to the rules in RFC -6265 spec.
- [x] Client can remove a specific session  cookie from the cookie store.
- [x] All session and persistent  cookies relevant to the request domain and path can be retrieved from the cookie store and added to the request (in "Cookie" header) according to the rules in RFC-6265 spec.
- [x] Implement concurrency management for cookies to avoid issues occurred when  adding cookies to cookie store simultaneously and write unit test and integration test for that.-  #19995
- [x] Change Integration tests as the client side implementation in a main function and add more unit tests and integration tests. -#19868
- [x] Manage persistent cookies - #19780 
    - [x] Add persistent cookies to the cookie store using  a database. - #20163
    - [x] Get the persistent cookies relevant to the request domain and path. - #20168
    - [x] Remove all expired cookies  and any specific persistent cookie in the cookie store. - #20169
- [x] Manage limits on the number  of cookies that can be stored. -  #19865
- [x] APIs for getting cookies by cookie name and cookie domain.
- [x] APIs for removing cookies by cookie domain and removing all the expired cookies in the cookie store.

Implemented Test cases :
- [x] Integration test for sending a request for the first time by the client , sending both persistent and session cookies in the inbound response and sending a request again by the client with the relevant cookies..
- [x] Integration test for removing  session cookie by client .
- [x] Integration test for removing  persistent cookie by client .
- [x] Integration test for sending similar cookies by server.
- [x] Integration test for removing  session and persistent cookies by server.
- [x] Unit test and negative tests for adding a session cookie to the cookie store, getting session cookies from the cookie store ,remove a specific session cookie from the cookie store by client, removing cookies in the cookie store by server, adding cookies to the request and response, getting cookies from the response and request . 
- [x] Unit test and negative tests for adding a persistent cookie to the cookie store, getting persistent cookies from the cookie store ,remove a specific persistent cookie from the cookie store by client, clear all cookies in the cookie store, test to  check maximum number of cookies and cookies per domain when adding a cookie to cookie store, get cookies by name & domain and remove cookies by domain.

To-do: 
- [ ] Allow or block sending cookies for third party requests . - #19775
 - [ ] Manage permission for using cookies for websites. (allow & block) - #19777

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by chamil321** [comment]
Closing the issue as we have released the feature in v1.2.0. The remaining tasks will be tracked via #19775 #19777.
