### ISSUE TITLE
Issues in type-checking for mapping and list constructors

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#21345]
**Description:**
Creating an issue to track the following issues related to $title.

- [ ] Issue in inferred type for list constructor with any, anydata, etc. #20773
- [ ] Issue with tuples with union-typed tuple rest descriptors #21281
- [ ] Array length validation does not happen for union expected types #21247
- [ ] Creating a tuple by specifying less members than the expected type is not allowed even when FillMember is applicable #21338

- [ ] Ambiguous type error when using a mapping constructor expression with a union of maps expected type #21282 

**Related Issues:**
https://github.com/ballerina-platform/ballerina-lang/issues/21222
