### ISSUE TITLE
Functional constructor syntax for XML item types

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#22431]
We need to support functional constructors for XML subtypes. Thsi include xml:Element, xml:Comment etc,.

This includes adding support for actual functional constructors and binding patterns.

Sub-tasks:

- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/22635 Add functional constructors for XML subtypes
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/22637 Add destructuring binding pattern support for xml Functional constructors
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/22638 Add match binding pattern support for xml Functional constructors

**Comment by rdhananjaya** [comment]
Closing as spec no longer support functional constructors for Swan Lake release
