### ISSUE TITLE
Implement new `error` design 

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-lang#23098]
Implementation issue to track #https://github.com/ballerina-platform/ballerina-spec/issues/509

**Sub Tasks**

Error Type descriptor 
- [x] the error reason string is removed
- [x]  the error type descriptor has a single type parameter, which specifies the detail record

Update to Error Detail Record and Constructor 
-  [x] `message` and `cause` move from the detail record into the error itself
   - [x]  the type is `string` and `error?` respectively
   - [x]  the message is required
   -  [x] the cause defaults to `()` if not specified
   - [x]  they are specified by positional arguments to the error constructor
   -  [x] lang.error provides `message` and `cause` functions to access them
-  [x] the required type of detail record is `map<anydata|readonly>` (with no predefined fields)
- [x]  the positional parameters of error constructors specify the message and cause
-  [x] if the error constructor uses a type that does not specify a detail record type with individual fields, then named arguments can be used to specify arbitrary fields
-  [x] if the error constructor uses a type that does specify a detail record type with individual fields, then the named arguments can only be used to specify those fields; other fields must be specified with `...` and a mapping constructor (not sure if this functionality is really necessary)

Distinct Error Type 
- [x] Implement Distinct Error syntax
- [x] Implement type-id support

- [x] Fix failing stdlib module tests due to error change #23594
- [x] Fix failing jballerina-unit-tests due to error change.
- [x] Fix and align error destructuring binding pattern https://github.com/ballerina-platform/ballerina-lang/issues/23591
- [x] Fix and align error destructuring assignment binding pattern https://github.com/ballerina-platform/ballerina-lang/issues/23592
- [x] Re-enable tests disabled with `brokenOnErrorChange` #23702
- [ ] Align Ballerina runtime generated errors to new error format https://github.com/ballerina-platform/ballerina-lang/issues/23746
- [x] Align error values stringValue method with the spec https://github.com/ballerina-platform/ballerina-lang/issues/23897
- [x] Support intersection types for error type #24403
- [x] Need to check and support error cause in QueryDesugar #23858
- [x] Fix error match pattern to support error cause #23593

**Comment by hasithaa** [comment]
This is done.
