### ISSUE TITLE
Complete support for `T & readonly` 

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#23383]
**Description:**
https://github.com/ballerina-platform/ballerina-lang/pull/22965 introduced support for `T & readonly`.

The remaining sub-tasks are as follows.

- [x] Support `T & readonly` for table types #23032
- [x] Disallow langlib methods that modify the value on immutable values #22964 
- [x] Allow constructing values with their read-only bit on with a type-cast-expr `<readonly>` #22954
- [ ] Allow using the type-test for `readonly` with selectively immutable basic types #22785
- [x] Support specifying readonly fields in the mapping constructor expression #23663
- [x] The type for a `readonly T x;` record field needs to be set as `T & readonly` #23257
- [x] Identify and fix issues in `xml<T> & readonly` #23276
- [x] Objects should be a selectively immutable type #23420
- [x] If all the fields in a closed record typedesc are `readonly` the record type itself should be a subtype of `readonly` #23464
- [x] Record sub-type checks need to consider the readonly flag #23468
- [x] Support readonly object fields #23552
- [x] Fix missing flags in BIRPackageSymbolEnter and add balo tests for immutable types and readonly fields #23587

**Comment by MaryamZi** [comment]
All the issues mentioned in the description have been fixed, except for #22785 which is part of a broader issue (see https://github.com/ballerina-platform/ballerina-lang/issues/22785#issuecomment-649235972).

Closing this since the major features have been completed and other minor tasks/improvements are being tracked by separate issues.
