### ISSUE TITLE
Complete match statement parsing

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#24388]
**Description:**

Spec: https://ballerina.io/ballerina-spec/spec.html#match-pattern-list

- [x] Constant match pattern
- [x] wildcard match pattern
- [x] var binding-pattern (#24290)
- [x] List match pattern (#24291)
- [x] Mapping match pattern (#24292)
- [x] Functional match pattern (#24293)
