### ISSUE TITLE
[Compiler APIs] Add an API to query semantic information of a program

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-lang#25330]
Need to add an API to query semantic information about a program. This high level task can be broken down to multiple sub tasks. This issue is to keep track of those sub tasks:

- [x] #25327 Capture position information of symbols in the symbol itself
- [x] #25328 Add an API to retrieve the in-scope symbols for a given cursor position
- [x] #25329 Add an API to retrieve the symbol at a given cursor position

**Comment by SupunS** [comment]
Closing, since all the sub tasks are completed
