### ISSUE TITLE
Provide support for jvm reserved characters in identifiers

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-lang#25519]
**Description:**

This is to track the progress of quoted identifier implementation

**Related Issues (optional):**
#19478 , #18158 

**Task list**

- [x] Encoding, Decoding schemes
- [x] Variables
  - [x] Constants, Final, Global variables
  - [x] Local variables
- [x] Functions 
  - [x] Function names
  - [x] argument names
- [x] Structured type (including fields, attached functions)
  - [x] Records
  - [x] Objects 
    - [x] client objects
- [x]  workers 
   - [x] worker interaction
- [ ] Service
  - [x] Service Name
  - [ ] Resource functions
- [ ] Decoding for runtime invocation (eg. toString(), member access)

**Suggested Labels (optional):**
Area/jBallerina   , Type/improvement

**Comment by HindujaB** [comment]
This can be tracked inside the issue #18158  itself
