### ISSUE TITLE
Implement new service typing proposal

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-lang#26064]
**Description:**
Proposal: https://docs.google.com/document/d/1HOYNcf68p06HTUe3jn-_Iaia626dBmHyBqG3yWLmt14/edit#

Subtasks:

- [ ] Support declaring service object types #26239
- [ ] Support service class declarations #26240
- [ ] Support service declarations #26238
- [ ] Support service constructor expressions #26241
- [ ] Re-enable (or remove) tests disabled due to service change https://github.com/ballerina-platform/ballerina-lang/issues/26868

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
This is implemented.
