### ISSUE TITLE
Complete support for `isolated`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-lang#26713]
**Description:**
Creating this issue to track the remaining tasks and deviations.

Features/Pending Design

- [x] Introduce isolated module level variables #25898 
- [x] Implement isolation inference #26045
- [x] Implement isolated services #27056
  - [x] Service references should be allowed in isolated functions only if the type is a subtype of `readonly` #26126
- [x] Introduce support for implicitly isolated object constructor expressions #26704
- [ ] Analyze closure isolated-ness wrt to the stack frame #25918

Spec Deviations/Bugs

- [x] Bound method access should be considered `isolated` only if both the method and the object are `isolated` #26701
- [x] Allow function-call-exprs with function parameters annotated with `@isolatedParam` in isolated functions #26601
- [x] Mark relevant stream/query langlib methods as `isolated` #26575
- [x] `StreamImplementor` methods have to be `isolated` #26677
- [x] Fix isolated expression analysis for variable references #26706
- [x] [Isolation] Fix deviations in copy in/out analysis #26766
- [x] [Isolation] Cannot copy in a value using clone/cloneReadOnly #26785
- [x] Incorporate changes for isolated object constructor expressions #26700

**Comment by MaryamZi** [comment]
Closing this issue since everything that is in the spec has been implemented. 

https://github.com/ballerina-platform/ballerina-lang/issues/25918 needs to be finalized in the spec to introduce relevant changes.
