### ISSUE TITLE
Language Server Swanlake Roadmap

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-lang#28325]
**Description:**
This is to capture the roadmap of the language server.

#### Language Features

- [x] Auto-completion (Deliver on: By RC1)
                1. Sorting completion Items [On going]
                2. Spec coverage [On going]
                3. Bug fixes [On going]
- [x] Hover (Deliver on: By Beta1)
- [x] Signature help (Deliver on: On Beta1)
- [x] Definition (Deliver on: By RC1)
                1. Within single file [completed]
                2. Within a project  [completed]
                3. Standard libraries and other central modules pulled
- [x] References (Deliver on: By RC1)
                1. Within single file [completed]
                2. Within a project  [completed]
                3. Standard libraries and other central modules pulled
- [x] Document Symbol (Deliver on: Beta4)
- [x] Code Action (Deliver on: By RC1)
- [x] Code Lens (Deliver on: By RC1)
- [x] Formatting (Deliver on: By Beta)
- [x] Range formatting (Deliver on: By Beta)
- [x] Rename (Deliver on: By Beta1)
                1. Within single file [Completed]
                2. Within a project  [Completed]
- [x] Folding Range (Deliver on: By Beta)
- [x] Semantic Tokens (Beta4)

#### Workspace Features

- [x] Workspace Symbols (Deliver on: Post Swanlake)
- [x] File Operations event (Deliver on: By Beta) #28650 
- [x] Workspace Event handling (Folders, file creations and etc.) #28650 

#### Diagnostics

- [x] Ballerina Diagnostics (syntax and semantic)
- [x] Meta-file diagnostics (Deliver on: By Beta)

#### Extensions Model

- [ ] Code Actions
                1. AI Data Mapping [Completed]
                2. Open API
- [x] Service extensions
                1. Move out diagram Service and related services to individual components
- [x] Completion Providers

**Comment by IMS94** [comment]
Closing this since the mentioned tasks were completed by Swan Lake GA
