### ISSUE TITLE
Implement DFS style type resolution

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-lang#32617]
**Description:**
This test case is disabled by PR:https://github.com/ballerina-platform/ballerina-lang/pull/32601
This issue is to track and enable the test case.

**Test case is modelled around HTTP module which showed intermittent fails.**

**TODO**
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/32070
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/32044
- [x] revert the PR https://github.com/ballerina-platform/ballerina-lang/pull/32601
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/33331

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
This is not yet resolved. 
Need to revert test diable on this PR after fix
https://github.com/ballerina-platform/ballerina-lang/pull/33328
