### ISSUE TITLE
Multiplicative operations between union types of user defined subtypes of float and decimal gives compile error

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#33265]
Consider the following code

```ballerina
import ballerina/io;

type Floats1 -2.0f|-1.0f|0.0f|1.0f|2.0f;
type Floats3 Floats1;

public function main() {

    Floats3 a = 2.0;
    Floats1|float d = 1.0f;
    io:println(a/d);  // should print 2.0
}
```

Compiling the above code gives below error. 
```

operator '/' not defined for 'gimantha/myProj:0.1.0:Floats3' and '(-2.0f|-1.0f|0.0f|1.0f|2.0f|float)'
error: compilation contains errors
```
Similar error is given by the compiler for multiplication and remainder as well

#### TODO
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33265
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/32928
- [x] https://github.com/ballerina-platform/ballerina-lang/issues/32828

**Comment by KRVPerera** [comment]
May be related to https://github.com/ballerina-platform/ballerina-lang/issues/3305 also

**Comment by MaryamZi** [comment]
Fixed in #33614, merged to master in #33977.
