### ISSUE TITLE
Fix other edge cases of object constructor level closures

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-lang#34395]
This issue is to track the edge cases of https://github.com/ballerina-platform/ballerina-lang/pull/32697 .

**Comment by gimantha** [comment]
Consider the following case

```ballerina
function foo() returns any {
    final int i = 10;

    object {
        function bar(int b) returns int;
        } zz = object {
            function bar(int b) returns int {
                var x = function () returns int {
                    return b + i;
                };
                return x();
            }
        };

        return zz.bar(4);
}
```
Running above function in jUnit gives below error

```
org.ballerinalang.core.util.exceptions.BLangRuntimeException: Error while invoking function 'foo'
	at org.ballerinalang.test.BRunUtil.invoke(BRunUtil.java:460)
	at org.ballerinalang.test.BRunUtil.invokeFunction(BRunUtil.java:1271)
	at org.ballerinalang.test.BRunUtil.invoke(BRunUtil.java:205)
	at org.ballerinalang.test.BRunUtil.invoke(BRunUtil.java:1314)
	at org.ballerinalang.test.bala.types.TTT.testTypeOfNeverReturnTypedFunction(TTT.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by hasithaa** [comment]
Following program also crashes at runtime. 

```ballerina
public function main() {
    int i = 10;     // Unused variable
    Foo foo = object {
        function foo() returns int {
            function () returns int xx = () => i;   // Runtime crash.
            return xx();
        }
    };
    panic error(foo.foo().toString());
}

type Foo object {
    function foo() returns int;
};
```

[2021-12-17 22:25:23,887] SEVERE {b7a.log.crash} - Index 0 out of bounds for length 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at $value$$anonType$_0.call(c.bal)
        at c.main(c.bal:12)
        at $_init.$lambda$main$(.)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by KRVPerera** [comment]
Improve coverage too...
https://github.com/ballerina-platform/ballerina-lang/pull/34374/checks?check_run_id=4563250241

**Comment by KRVPerera** [comment]
### TODO

- [ ] https://github.com/ballerina-platform/ballerina-lang/pull/32697
    - [ ] annotations
         - [x] object ctor type annotations 
         - [ ] field annotations
         - [ ] methods annotations may be related to : https://github.com/ballerina-platform/ballerina-lang/issues/28439
    - [ ] propagate arrow expression like closure support expressions closures through OCE
    - [ ] multi level closures
        - [ ] OCE as a class field 
        - [ ] refactor attached methods closure maps usage
        - [ ] boundaries break inside classes and any other closure supported expressions
        - [ ] seamless boundaries through free methods (non attached)
        - [ ] seamless through other expressions
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/34396
- [x] unused variables warnings
  - [ ] test coverage
- [ ] tests beyond module boundaries
