### ISSUE TITLE
[Task]: Bump `mime4j`, `okio` and `woodstox` dependency versions

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#41193]
### Description

- [x] Axiom using `mime4j 0.7.2` which has a vulnerability CVE-2022-45787, need to update to `0.8.9`.  #41184
- [x] Remove transitive dependency from axiom to `org.codehaus.woodstox:woodstox-core-asl`  since we are using `fasterxml:woodstox-core`.  #41184
- [x] Bump OkIO version due to CVE-2023-3635 #41152

Internal issue: https://github.com/wso2-enterprise/internal-support-ballerina/issues/401

### Related area

-> CICD

**Comment by rdulmina** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/41152 and  #41184
