### ISSUE TITLE
[Improvement]: Improve compiler diagnostics

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-lang#42124]
### Description

The current format of compiler error diagnostics in Ballerina could be enhanced to provide more helpful information to users. Currently, it outputs errors in the following format:
```
ERROR [filename:(startPosition, endPosition)] error message
```
This format lacks detailed information about the area of the error code, making it less user-friendly compared to other compilers like Rust. By enhancing the output to include the area of the error code, users will have a clearer understanding of where the error occurred, which can significantly improve the user experience.

### Describe your solution(s)

- Modify the compiler error diagnostics format to include the area of the error code.

### Related area

-> Compilation

**Comment by RadCod3** [comment]
#### 21/02/2024 Update
- Semantic diagnostics rendering works.
- Syntax Diagnostics,
  - Used args that are passed into createDiagnostic method to get the missing token/keyword for BCE0001 to BCE0400. https://github.com/ballerina-platform/ballerina-lang/blob/838820f39c3b737af03a00d1819b1c807ed6c917/compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/SyntaxErrors.java#L96
- Used jline for resizing diagnostic rendering based on terminal window size.

**Comment by RadCod3** [comment]
### Tasks
- [ ] Improve Diagnostic Rendering using Diagnostic API and Syntax API.
- [ ] Add a `bal explain <error_code>` command to explain error codes. 
- [ ] Prepare Diagnostic structure guide
