### ISSUE TITLE
[New Feature] Extending build-tool integration with subcommands, central delivered tools and adding to Dependencies.toml 

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-lang#42155]
### Description
Currently, Ballerina provides `bal tool`, a way for developers to extend the CLI functionalities by introducing new commands. These tools/ commands are shipped as packages in Ballerina Central and are managed by the inbuilt `bal tool` command.

With update 9, we are also allowing tools to be integrated with the build command. They will run as a pre-build task. (Design doc - https://docs.google.com/document/d/1XsZK3UlqXv4TLEgRKVc0UBRRilLTmLZ1heDTmIRuylE/edit?usp=sharing).  

### Describe your problem(s)
1. However, the build integrated tools need to be packed in the distribution(bre/lib) to be used. There is no way to externally publish and use the build integrated tools.
2. We need to support integration of subcommand of tools (eg:- health.fhir) with build.
3. For predictable builds, we need to lock tool versions in Dependencies.toml

### Describe your solution(s)
Use the existing strategy of delivering `bal tools` to distribute the tools integrated with build.
Design doc - https://docs.google.com/document/d/1XsZK3UlqXv4TLEgRKVc0UBRRilLTmLZ1heDTmIRuylE/edit#heading=h.3odx7sx4desy 

### Related area
-> Compilation

### Related issue(s) (optional)
https://github.com/ballerina-platform/ballerina-lang/issues/41415

### Suggested label(s) (optional)
No response

### Suggested assignee(s) (optional)
No response

Related issues

**Comment by gayaldassanayake** [comment]
Following are the tasks that have to be completed under this feature.

## Phase 1
- [x] Picking tools from a URL class loader
- [x] Dependency version resolution
- [x] Automatically pulling tools
- [ ] Restrict tools from having a DOT in id
  - [ ] In pack
  - [ ] In push
  - [ ] Central 
  - [ ] Tool Loading
- [x] Recording in Dependencies.toml
- [x] Supporting sub commands
- [ ] Test tool resolution endpoint (Blocked on endpoint implementation)
- [ ] Change the getName() return type to String[]
- [ ] Local repo support - phase 2?
- [ ] Testing
    - [ ] Manual testing of all scenarios
    - [ ] Lang tests
    - [ ] Distribution tests
- [ ] Documentation
    - [ ] Update the developer guide
    - [ ] Website documentation
    - [ ] Release notes

## Phase 2
- [ ] Minimum compatibility version
- [ ] Introduce a print API for the developers

**Comment by gayaldassanayake** [comment]
The initial PR has been merged. The remaining tasks are,
- [ ] Improve the code coverage
- [ ] Reuse code from package resolution - https://github.com/ballerina-platform/ballerina-lang/issues/42348 
- [ ] Minimum compatibility version (Phase 2)
- [ ] Local repo support (Phase 2)
