### ISSUE TITLE
[Task]: Implement Static Code Analysis Support for Ballerina

### ISSUE THREAD

**Issue by Xenowa** [ballerina-platform/ballerina-lang#42260]
### Description

Static code analysis examines code without execution, identifying potential issues like bugs, security vulnerabilities, and style violations. It improves software quality by early issue detection, creating better maintainability, and providing enhanced security.

Each programming language has its own unique syntax and semantics. Therefore, effective static code analysis requires tools specifically designed for the language being analyzed. These tools leverage the language's specific characteristics to perform more in-depth and accurate analysis.

Existing static code analysis tools like [SonarQube](https://www.sonarsource.com/products/sonarqube/) rely on these language-specific code analyzers to extract information and report issues.

This effort focuses on developing a Ballerina tool to perform static code analysis based on sets of rules and report analysis issues to  various static code analysis platforms.

Contains steps to Implement [#42256](https://github.com/ballerina-platform/ballerina-lang/issues/42256#issue-2162985166)

#### [Phase 1] Creating the core analyzer:
- [ ] Implement core analyzer with analysis report generation
    - Implement a analyzer to identify Ballerina files and obtain its syntax tree and other relevant properties
    - Implement feature to generate a JSON report in a target directory at the end of the analysis
    - Implement feature to specify target directory to generate the report at the end of the analysis

- [ ] Implement HTML report generation
    - Implement user-friendly report to visualize analysis issues

- [ ] Implement core rule: identify usage of checkpanic keyword
    - Develop a syntax tree traversal mechanism to identify ‘checkpanic’ keyword usage in Ballerina files

- [ ] Implement filtering analysis issues for core rules
    - Develop a mechanism for including and excluding core rules in in the console, to generate customized analysis results

- [ ] Implement `Scan.toml` based scan tool behavior configuration
    - Identify configurations provided to modify scan tool behavior
    - Develop a mechanism to identify a load configurations from a local or remote `Scan.toml` file

#### [Phase 2] Introduce extension points for the core analyzer
- [ ] Implement extension for platform specific issue reporting

- [ ] Implement extension for supporting additional analysis capabilities of scan tool via compiler plugins

#### [Phase 1] Creating a SonarQube Ballerina Plugin
- [ ] Add feature to report core analysis issues generated via Ballerina scan tool when a scan is triggered via the sonar-scanner CLI

#### [Phase 2] Extending functionalities of SonarQube Plugin
- [ ] Add feature to report core analysis issues generated via Ballerina scan tool when a scan is triggered from the Ballerina scan tool

- [ ] Add feature to report custom analysis issues generated via Ballerina scan tool

### Related area

-> Other Area

**Comment by Xenowa** [comment]
**24/04/2024 Update**

- Implementations for static code analysis support for Ballerina have already been created in [ballerina-scan-tool](https://github.com/Xenowa/ballerina-scan-tool) repository and changes are steadily being ported to [static-code-analysis-tool](https://github.com/ballerina-platform/static-code-analysis-tool)
- Several class-loader-related issues that prevent casting objects passed from Ballerina tools to compiler plugins have been addressed:
    - https://github.com/ballerina-platform/ballerina-lang/issues/41957
    - https://github.com/ballerina-platform/ballerina-lang/issues/42312
- Identified and sent a PR to fix a workflow and test misconfigurations in the setup-ballerina action which prevents installation of the latest Ballerina version for Windows builds:
    - https://github.com/ballerina-platform/setup-ballerina/issues/6
    - https://github.com/ballerina-platform/setup-ballerina/pull/7

**Comment by Xenowa** [comment]
**29/06/2024**

- [Demonstrations](https://drive.google.com/file/d/1iqu8ZEtTtJaPJGXZqXqrStYrvloP4gru/view) for creating a static analysis compiler plugin and a static code analysis platform plugin to extend the scan tools capabilities has been made.
