### ISSUE TITLE
[Improvement]: Optimize the compile time memory usage

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-lang#43125]
### Description

According to https://github.com/ballerina-platform/ballerina-lang/issues/42860#issuecomment-2199543095 We need to Optimize the compile time memory usage since compiling large dependencies uses nearly 1GB of heap memory. 

Master branch Heap usage when compiling https://github.com/ballerina-platform/module-ballerinax-health.hl7v2/tree/main/hl7v27
<img width="678" alt="before" src="https://github.com/user-attachments/assets/8e2e738c-0c65-4fee-86d3-7f3f173521d5">

Analyze the heap usage when compiling https://github.com/ballerina-platform/module-ballerinax-health.hl7v2/tree/main/hl7v27

- [x] Remove creating `HashMap` for `jarEntries` in `JvmPackageGen` https://github.com/ballerina-platform/ballerina-lang/issues/43222
- [x] Clean syntax tree before codegen https://github.com/ballerina-platform/ballerina-lang/issues/43226
- [x] Reduce BLangDiagnosticLocation to create LineRange and TextRange only when needed  https://github.com/ballerina-platform/ballerina-lang/issues/43223

**Comment by rdulmina** [comment]
Please find the link to the rough document of the progress https://docs.google.com/document/d/1WmS4CneYr_3i15ON059LKveaISSPjcMGW-gpnojFPn4/edit?usp=sharing

**Comment by rdulmina** [comment]
`CompiledJarFile.jarEntries` is a `HashMap` object with contributes to 61.5MB of the Heap size. The usage of this map is to `create java.io.ByteArrayOutputStream` at the later part of the code. It was possible to create `ByteArrayOutputStream` directly without creating a `HashMap`. Hence did a fix to create `ByteArrayOutputStream` directly instead of creating a `HashMap` by introducing `JAREntries` class. Was able to gain 42MB memory reduction by this fix. Below is the memory usage at a specific point of the program execution

Before
![Screenshot 2024-07-21 at 11 31 25](https://github.com/user-attachments/assets/33b30e12-4997-4414-9206-a6420642b151)

After
![Screenshot 2024-07-21 at 10 52 56](https://github.com/user-attachments/assets/80a42788-e934-4fa5-8bd1-8887587934a9)

**Comment by rdulmina** [comment]
`ModulePartNodes` takes around 107MB. And I did a fix to nullify them before the codegen phase. Was able to free around 100MB by that fix. But experiencing some test failures. Currently looking into that. Below is the Heap usage with several other fixes

<img width="678" alt="Screenshot 2024-07-24 at 12 16 05" src="https://github.com/user-attachments/assets/19b5c425-fc1e-4e07-9a85-ea06e6ab5cd9">

**Comment by rdulmina** [comment]
`LinePosition` objects take around 21MB. Did a fix to [Reduce BLangDiagnosticLocation to create LineRange and TextRange only when needed ](https://github.com/ballerina-platform/ballerina-lang/pull/43208)

**Comment by rdulmina** [comment]
Heap usages by live objects after fixes

![Screenshot 2024-07-31 at 16 45 28](https://github.com/user-attachments/assets/a0418fce-3eeb-4fa1-890d-5f1831727680)

Heap usage by all the objects after fixes

![Screenshot 2024-07-29 at 11 34 24](https://github.com/user-attachments/assets/f2df257e-8863-4ea3-89e6-2c5995d77b3c)

### In the graph what it shows is the heap usage by all the objects. If we consider only the live objects we have around 700MB of free Heap space all the time after the fixes

**Comment by rdulmina** [comment]
Closing this as all the tasks are done
